### ISSUE TITLE
Lacie Private Public issues with Yosemite

### ISSUE THREAD

**Issue by analogdaniel** [osxfuse/osxfuse#189] opened 2015-01-12 09:41 UTC
hello, I just updated to Yosemite and cannot access my Lacie hard-drive's Private-Public folder. The first message I get is...
![screen shot 2015-01-12 at 4 22 07 pm](https://cloud.githubusercontent.com/assets/10496521/5701105/9e34407a-9a79-11e4-9490-2399f79c961e.png)
and then

![screen shot 2015-01-12 at 4 22 21 pm](https://cloud.githubusercontent.com/assets/10496521/5701112/acdd21be-9a79-11e4-99de-a21557f9ecfb.png)

i've tried contacting lacie and apple. I also have an older Mac running 10.6.8. when i try to access the folder there, I get a different error message, but still cannot access.
Thanks!

**Comment by fhgwright** [comment] 2015-01-16 22:07
That doesn't tell you anything about what version of OSXFUSE it's trying to install or where it's getting it.

What happens if you install the latest OSXFUSE from the OSXFUSE website (checking the MacFUSE compatibility checkbox in the installer options, of course)?

If this problem first appeared on Yosemite, it's likely to be related to Yosemite's new signature requirements for kernel extensions.  The official OSXFUSE releases all have acceptably signed kexts, but other builds usually don't.

**Comment by analogdaniel** [comment] 2015-01-18 18:54
Thanks for the reply! 
When I download the latest OSXFuse, everything seems fine, but then when I try to access the Private-Public folder, I get the above message as if I didn't already have OSXFuse installed.

**Comment by fhgwright** [comment] 2015-01-18 21:50
Well, "everything seems fine" is a bit lacking in detail. :-)

You can check the installed version of OSXFUSE from the "FUSE for OS X" preference pane, unless you deselected that option during the install.  Unfortunately, that doesn't tell you whether the MacFUSE compatibility libraries are installed.

If you don't have the preference pane, you can check the version from a Terminal window with the following command:

  /Library/Filesystems/osxfusefs.fs/Support/mount_osxfusefs -h 2>&1 | grep version

That should show something like:

OSXFUSE mount version 2.7.4

If that looks kosher, you can check whether the MacFUSE compatibility libraries are present with:

  ls -l /usr/local/lib/libmacfuse*

That should show something like:

-rwxr-xr-x  1 root  wheel  49896 Jan  7 16:17 /usr/local/lib/libmacfuse_i32.2.dylib
lrwxr-xr-x  1 root  wheel     22 Jan 18 13:15 /usr/local/lib/libmacfuse_i32.dylib -> libmacfuse_i32.2.dylib
-rwxr-xr-x  1 root  wheel  49896 Jan  7 16:17 /usr/local/lib/libmacfuse_i64.2.dylib
lrwxr-xr-x  1 root  wheel     22 Jan 18 13:15 /usr/local/lib/libmacfuse_i64.dylib -> libmacfuse_i64.2.dylib

If that looks kosher, you can see if the kernel extension got loaded (after attempting the LaCie access), and whether the MacFUSE compatibility mode got enabled, with:

  sysctl osxfuse.control.macfuse_mode

That should show one of three responses:

top level name osxfuse in osxfuse.control.macfuse_mode is invalid

That means that the kernel extension didn't get loaded, probably due to some compatibility issue with the LaCie software.

osxfuse.control.macfuse_mode: 1

That means that the extension got loaded *and* the compatibility mode got enabled, so whatever is wrong is probably a more subtle compatibility issue with the LaCie software.

osxfuse.control.macfuse_mode: 0

That means that the extension got loaded, but the compatibility mode didn't get enabled.  In that case, you might try:

  OSXFUSE_MACFUSE_MODE=1 /Library/Filesystems/osxfusefs.fs/Support/load_osxfusefs

Then check the sysctl again.  If it's correct now, try the LaCie access again.  If that works, you at least have a workaround.

Now we'll see if the formatting survives the forum...

**Comment by analogdaniel** [comment] 2015-01-19 21:02
I went through your terminal steps, and everything came out the way you said except for the last part.
sysctl osxfuse.control.macfuse_mode 
sysctl: unknown oid 'osxfuse.control.macfuse_mode'
admins-MacBook-Pro:~ admin$ 
Does this help?
I put the full terminal info below too.
Thanks again!
Last login: Mon Jan 19 06:39:45 on ttys000
admins-MacBook-Pro:~ admin$ /Library/Filesystems/osxfusefs.fs/Support/mount_osxfusefs -h 2>&1 | grep version
OSXFUSE mount version 2.7.4
admins-MacBook-Pro:~ admin$ 
admins-MacBook-Pro:~ admin$ ls -l /usr/local/lib/libmacfuse*
-rwxr-xr-x  1 root  wheel  49896 Jan  8 07:17 /usr/local/lib/libmacfuse_i32.2.dylib
lrwxr-xr-x  1 root  wheel     22 Jan 19 06:08 /usr/local/lib/libmacfuse_i32.dylib -> libmacfuse_i32.2.dylib
-rwxr-xr-x  1 root  wheel  49896 Jan  8 07:17 /usr/local/lib/libmacfuse_i64.2.dylib
lrwxr-xr-x  1 root  wheel     22 Jan 19 06:08 /usr/local/lib/libmacfuse_i64.dylib -> libmacfuse_i64.2.dylib
admins-MacBook-Pro:~ admin$ sysctl osxfuse.control.macfuse_mode
sysctl: unknown oid 'osxfuse.control.macfuse_mode'
admins-MacBook-Pro:~ admin$

**Comment by fhgwright** [comment] 2015-01-19 21:58
That means that the kernel extension didn't get loaded when you attempted the access.  Most likely that means that there's a compatibility issue between the LaCie filesystem and the library that would have other consequences as well, but on the off-chance that the problem is limited to the extension loading, you could still try the load_osxfuse command that I posted above to see if it helps.

You're getting a different error message for the nonexistent sysctl than what I posted, but that's just a difference between Mavericks and Yosemite.

**Comment by Mog65** [comment] 2015-02-01 02:07
Hi
I've just had exactly the same problems after installing yosemite yesterday. I have followed all of your instructions above but I still get the following error.
![screen shot 2015-02-01 at 1 00 09 pm](https://cloud.githubusercontent.com/assets/10792328/5990710/1b80a73c-aa13-11e4-95f7-fb7962fd6792.png)
Any ideas? I have 2 documents on that portion of the drive that I really need to access and don't have a copy of them anywhere else!

**Comment by analogdaniel** [comment] 2015-02-01 02:47
I wish I had better news, but I ended up having to wipe my computer and reinstall a version of Mavericks in able to access the Private-Public folder. I didn't find anything else that worked for me.

**Comment by Mog65** [comment] 2015-02-01 02:58
Bugger. I think I will try and access it from someone else's Mac that still has Mavericks and copy those 2 files off! Very annoying!!! Especially as Apple recommend the LaCie drives.

**Comment by fhgwright** [comment] 2015-02-01 19:44
That's why, whenever I upgrade to a new major version of OSX, I always install it to a new drive (or partition) and keep the old one. :-)

In the non-working Yosemite case, nobody has posted the results of manually loading the kernel extension before trying the LaCie access.  The minimal command for this (assuming the standard OSXFUSE is installed from this website) is:

/Library/Filesystems/osxfusefs.fs/Support/load_osxfusefs

That loads the kext without enabling MacFUSE mode, though the library normally does the latter when necessary.  If for some reason the latter aspect isn't working, then it can be done explicitly as follows:

OSXFUSE_MACFUSE_MODE=1 /Library/Filesystems/osxfusefs.fs/Support/load_osxfusefs

If either of the above works, then the compatibility issue is limited to getting the kext loaded (and the MacFUSE mode enabled), and you have a workaround.  It doesn't look like LaCie has an official fix yet.

In the working Mavericks case, it would be useful to determine what OSXFUSE version LaCie is using.  One way to do that (after having successfully accessed the Private-Public folder) is this:

kextstat | grep fuse

When the kext is loaded, that should produce a result something like this:

  147    0 0xffffff7f82a59000 0x16000    0x16000    com.github.osxfuse.filesystems.osxfusefs (2.7.4) <7 5 4 3 1>

The "(2.7.4)" above reflects the version.

Having determined the version used in the working Mavericks case, another useful Yosemite experiment would be to install the exact same (presumably older) version of OSXFUSE from this site (use the Archive link if it's not listed on the homepage).  Then load *it* manually via one of the commands above, and see if it makes LaCie happy.  Unfortunately, such an install can't coexist with an install of the current version, even if you rename it, due to internal knowledge of the file paths.  It can, however, coexist with a *MacPorts* install of OSXFUSE (which *knowingly* uses a different install location), but you still can't actually use both simultaneously.

There is a way to disable the kext signature check in Yosemite, but it disables *all* kext signature checks, and thus reduces kext security to pre-Mavericks levels.  It also involves a root-privileged tweak to nvram settings, which can render the machine unbootable if screwed up.

With regard to "Apple recommend the LaCie drives", there's probably nothing wrong with the *drive* - it's just that the way they implemented the "Private-Public folder" mechanism is fragile.  And in all fairness to LaCie, the "supported OS" list for that feature on their website says "Mac OS 10.5 - 10.9".

**Comment by bfleischer** [comment] 2015-03-16 12:48
I just performed a quick test with LaCie Private-Public 1.5.3 (released in October 2014) and osxfuse 2.7.5 on OS X 10.10. Creating, mounting, and using an encrypted volume worked perfectly fine for me.

When installing osxfuse make sure to check the "MacFUSE compatibility layer" installer option. Please note that the Homebrew/MacPorts version of osxfuse does not include the MacFUSE compatibility layer.

**Closed by bfleischer** 2015-03-16 12:48 UTC
