### ISSUE TITLE
sshfs + standby -> breaks kernel module???

### ISSUE THREAD

**Issue by 3s1d** [osxfuse/osxfuse#883] opened 2022-03-11 13:58 UTC
Hi,

I have the following versions: macOS12.2.1 + macFuse4.2.4

I have mounted my server via sshfs and everything worked fine. After lunch---the mac went into standby---the mount was no longer valid. A umount + remount (umount ... + sshfs ...) returned to following error:
`mount_macfuse: the macFUSE kernel extension is not loaded`

None seems to help... Like:
```
sudo kextunload -b io.macfuse.filesystems.macfuse
Executing: /usr/bin/kmutil unload -b io.macfuse.filesystems.macfuse
Error Domain=KMErrorDomain Code=71 "Kernel request failed: (libkern/kext) kext (kmod) start/stop routine failed (-603946985)" UserInfo={NSLocalizedDescription=Kernel request failed: (libkern/kext) kext (kmod) start/stop routine failed (-603946985)}
```

Exists there any solution? Is an automated unmount prior to standby possible?

Thanks
Juergen

**Comment by porg** [comment] 2022-05-13 10:18
No solution I know of.

But the root cause seems to be not necessarily the sleep/standby of your Mac per se /which happens after a certain longer time), but rather the termination of your ssh connection (which also happens after a certain longer time), which many many users testify at #45

If you concur with this analysis, you may close this issue here as duplicate and chime in over there.

**Closed as completed** 2024-03-12 11:24 UTC
