### ISSUE TITLE
open(2) returns EINTR for osxfuse files even when SA_RESTART is set

### ISSUE THREAD

**Issue by jacobsa** [osxfuse/osxfuse#228] opened 2015-08-13 22:59 UTC
I have a program that calls `sigaction(2)` for `SIGCHLD`, passing the `SA_RESTART` flag. The desire is that syscalls like `open(2)`, `read(2)`, etc. don't return `EINTR` when interrupted by this signal, but rather restart—my program doesn't want to have to handle `EINTR` explicitly for each call to these.

For plain old HFS+ files, I've never observed a problem with this. But if I receive `SIGCHLD` while opening a file on an osxfuse volume, `open(2)` returns `EINTR`.

The [man page](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man2/sigaction.2.html) for `sigaction(2)` says:

> Restart of pending calls is requested by setting the SA_RESTART bit in
> sa_flags. The affected system calls include open(2), read(2), write(2),
> sendto(2), recvfrom(2), sendmsg(2) and recvmsg(2) on a communications channel
> or a slow device (such as a terminal, but not a regular file) and during a
> wait(2) or ioctl(2).

Unfortunately the sentence structure here is ambiguous; you could read this as saying that `open(2)` will be restarted only for communications channels, or read that clause as only applying to `recvmsg(2)` and friends. For what it's worth, it appears that most people take the latter interpretation: see golang/go#11180, where people were surprised by me asking Go to handle `EINTR` in its `open(2)` wrapper.

Does it make sense (and is it even possible) for osxfuse to restart interrupted `open(2)` calls when `SA_RESTART` is set for the signal?

**Comment by bfleischer** [comment] 2015-11-10 00:21
I could not find any clear documentation whether it is ok for open (for regular files) to return EINTR. POSIX states:

> SA_RESTART
> [XSI] [Option Start] This flag affects the behavior of interruptible functions; that is, those specified to fail with errno set to [EINTR]. If set, and a function specified as interruptible is interrupted by this signal, the function shall restart and shall not fail with [EINTR] unless otherwise specified. If the flag is not set, interruptible functions interrupted by this signal shall fail with errno set to [EINTR]. [Option End] 

The man page for open lists EINTR as a possible return value:

> [EINTR] The open() operation is interrupted by a signal.

Unlike Linux, OS X does not provide public kernel API for blocking signals or checking which signal caused an interrupt.

This leaves two options:

* Return immediately, even for non-fatal signals. This is what we used to do.
* Let the user space file system handle all interrupts.

The first option can make it virtually impossible to complete long running I/O operations under high signal pressure. Therefore starting with version 3.0.9 we will go with the second option.

> Does it make sense (and is it even possible) for osxfuse to restart interrupted open(2) calls when SA_RESTART is set for the signal?

I think this is something that needs to be handled elsewhere, not in the VFS layer. The calling process needs a chance to handle the interrupt first, before the file system operation is restarted.

**Comment by jacobsa** [comment] 2015-11-10 00:39
Can you clarify what it means for the user space file system to handle all interrupts?

**Comment by bfleischer** [comment] 2015-11-10 00:44
If a process issuing a FUSE file system request is interrupted, the following will happen:

* If the request is not yet sent to user space, then an 'interrupted' flag is set for the request. When the request has been successfully  transferred to user space and this flag is set, an INTERRUPT request is queued.

* If the request is already sent to user space, then an INTERRUPT request is queued.

It is up to the user space file system implementation to handle the interrupt or to completely ignore it. I think most file systems are simply ignoring interrupts.

**Comment by bfleischer** [comment] 2015-11-10 00:47
Linux FUSE handles fatal signals by returning immediately given that the request has not been sent to user space, yet. On OS X it is not possible to differentiate between fatal and non-fatal signals using public kernel API.

**Comment by bfleischer** [comment] 2015-11-13 14:47
By accessing a (private) field in the `thread_t` data structure osxfuse can now differentiate between fatal and non-fatal signals. This means FUSE on OS X should now behave like FUSE on Linux:

```
Interrupting filesystem operations

If a process issuing a FUSE filesystem request is interrupted, the
following will happen:

  1) If the request is not yet sent to userspace AND the signal is
     fatal (SIGKILL or unhandled fatal signal), then the request is
     dequeued and returns immediately.

  2) If the request is not yet sent to userspace AND the signal is not
     fatal, then an 'interrupted' flag is set for the request.  When
     the request has been successfully transferred to userspace and
     this flag is set, an INTERRUPT request is queued.

  3) If the request is already sent to userspace, then an INTERRUPT
     request is queued.

INTERRUPT requests take precedence over other requests, so the
userspace filesystem will receive queued INTERRUPTs before any others.

The userspace filesystem may ignore the INTERRUPT requests entirely,
or may honor them by sending a reply to the _original_ request, with
the error set to EINTR.

It is also possible that there's a race between processing the
original request and its INTERRUPT request.  There are two possibilities:

  1) The INTERRUPT request is processed before the original request is
     processed

  2) The INTERRUPT request is processed after the original request has
     been answered

If the filesystem cannot find the original request, it should wait for
some timeout and/or a number of new requests to arrive, after which it
should reply to the INTERRUPT request with an EAGAIN error.  In case
1) the INTERRUPT request will be requeued.  In case 2) the INTERRUPT
reply will be ignored.
```

**Closed by bfleischer** 2015-11-13 14:47 UTC

**Comment by jacobsa** [comment] 2015-11-15 22:35
Thanks! Is osxfuse/kext@5a81338e1dead13a9b05eb50e4f93d6f63d4780b the relevant commit?

**Comment by bfleischer** [comment] 2015-11-15 23:30
> Is osxfuse/kext@5a81338 the relevant commit?

The following 4 commits are relevant:

* https://github.com/osxfuse/kext/commit/ec4b07040b59ff1579ac2936414f8d425e15c450
* https://github.com/osxfuse/kext/commit/5a81338e1dead13a9b05eb50e4f93d6f63d4780b
* https://github.com/osxfuse/kext/commit/81286a2a37177236e1666302baed81c79c226b4a
* https://github.com/osxfuse/kext/commit/7cb1619af13205ee0307d959e1558f7b3a44e6de

The issue you were seeing was a result of how the FUSE kernel extension used to handle signals while waiting for the user space file system daemon to respond to a file system request. On OS X there is no supported way (I know of) to block signals in kernel mode or to determine which signal caused an interrupt. This is why there have been only two options:

* Treat all signals a fatal and return immediately.
* Ignore all signals, including fatal ones.

Before version 3.0.9 all signals were treated as fatal. Between those two options this one is the 'safer' one, as we do not want file systems to hang the whole system. The problem is that it becomes virtually impossible to complete any I/O operation under high signal pressure.

That's why we needed a way to determine if a signal is fatal or not. I've added another kludge to make this feasible. This opens up a third option:

* We let non-fatal interrupts be handled by the user space file system daemon. Fatal ones are being handled in the FUSE kernel extension, unless the request has already been passed along to the user space file system daemon.

This third options deals really well with high signal pressure while still returning immediately in case of  fatal signals.

As for osxfuse/kext@5a81338:

The user space file system daemon is supposed to return `EINTR` in case it handles an interrupt that it received from the FUSE kernel extension. The FUSE kernel extension would then pass along `EINTR` to the process that actually started the file system operation. So far, so good.

But if `SA_RESTART`is set we need return `ERESTART` rather than `EINTR` for `SA_RESTART`to work. `msleep()` will return `ERESTART` in case `SA_RESTART` is set and `EINTR` otherwise. So we store this error code until the user space daemon returns. If it returns with `EINTR` we override this error code with the one returned by `msleep()` earlier.

On a side-node, OS X does not support restarting `open()` calls. It does not matter if we return `RESTART` or `EINTR` for `open()`.

**Comment by jacobsa** [comment] 2015-11-15 23:38
Thank you very much for the details; that's very helpful.
