### ISSUE TITLE
macFUSE 4.2.4 hungs on Monterey in case of invalid params

### ISSUE THREAD

**Issue by artpaul** [osxfuse/osxfuse#874] opened 2022-02-08 13:29 UTC
Hi,

I wonder to know if the 4.2.4 release on Monterey is still compatible with `https://github.com/osxfuse/fuse`? 

I'm trying to build a custom filesystem on top of macFuse, but I have some issues with mounting. When I statically link my binary with code from `github.com/osxfuse/fuse` I have a hung while mounting my fs. But when I dynamically linking with a library from `/usr/local/lib/libfuse.2.dylib` everything works fine.

**Comment by bfleischer** [comment] 2022-02-08 13:43
macFUSE 4.2.4 includes https://github.com/osxfuse/fuse (commit 16861a640619e4c13415a76587f9bb0eac8df10b). You might be missing some build flags when building your static version of libfuse. macFUSE has never shipped a static version of libfuse and I don't think I ever tried building a static version of the library. 

That being said, I don't recommend shipping your own version of libfuse. This will most definitely cause issues down the road and your file system will break.

**Comment by artpaul** [comment] 2022-02-08 21:28
Vielen Dank!

Actually, I found that the problem arises when the process terminates during initialization in case of some errors (ex. invalid params). Can be reproduced (at least at my machine) with the example binaries from `https://github.com/osxfuse/fuse`

Execution of
`./configure && make && ./example/hello <some-dir> -x`

will lead to 
`fuse: unknown option '-x'`

and to the process stucked in the uninterrupted wait state
`3656 s019  U     2:13AM   0:00.01 /Library/Filesystems/macfuse.fs/Contents/Resources/mount_macfuse <some-dir>`

Any ideas why it happen?

**Comment by octomike** [comment] 2022-02-10 14:25
Can confirm. I'm trying to find a solution to improve transfer speeds beyond 128KB/s.. A call to `sshfs` with invalid options leaves the OS (12.2, osxfuse 4.2.4) in an unusable state. Can't `umount`, `diskutil unmount force` etc.. I have to hard reset the machine.

Probably duplicate of #793

**Comment by unsound** [comment] 2022-04-23 04:09
Also seems to affect macFUSE 4.2.5, I'm getting a hang for passing an incorrect ```max_read``` value (```max_read=5324```). @bfleischer ping me if you want some help with this one. :)

**Comment by MarcoR83** [comment] 2022-05-18 13:16
unusable!  using 4.2.4 just was forced to hard reboot 2 times already monterey 12.4 x86

**Comment by bfleischer** [comment] 2024-03-16 12:52
The new 4.6.2 release addresses the hang. From the release notes:

> Perform `FUSE_INIT` handshake synchronously during `mount(2)` operation. When performing the handshake synchronously, we avoid hangs and we are able to error out of the mount process in case the handshake fails.
>
> We used to perform the handshake asynchronously. This has drawbacks and introduced several challenges. Most importantly, there is no guarantee the handshake will ever be completed by the file system daemon. This could result in lingering mount points.
>
> Performing the handshake synchronously makes initialization more robust.

Please let me know in case you are still running into mount issue.

The main motivation for performing the handshake asynchronously seems to have been to emulate the behavior on Linux and getting rid of the double-fork in libfuse when running the mount helper. This is a change we inherited from Fuse4X back in the day. 

The asynchronous handshake introduced several challenges and issues:
    
* `mount(2)` calls `VFSOP_MOUNT` followed by `VFSOP_GETATTR` before `mount(2)` returns. The volume will be in a mounted, but unusable state until the `VFSOP_GETATTR` call returns.
    
* The asynchronous handshake results in the volume being mounted as soon as `VFSOP_MOUNT` returns, but all processes accessing the volume being blocked until the handshake has been completed. It is not possible to unmount the volume until the `VFSOP_GETATTR` call returns.
    
* It is not a viable option to return fake attribute values from the `VFSOP_GETATTR` call because some of those values are being cached by macOS and never updated.
    
* There is no guarantee the `FUSE_INIT` handshake will ever be completed. libfuse mounts the volume before processing the command line arguments. In case the arguments are invalid, libfuse will not respond to the kernel extension's `FUSE_INIT` message.

**Closed as completed by bfleischer** 2024-03-16 12:52 UTC
Labels: bug
