### ISSUE TITLE
4.7.1 macFuse icon vanishes after mounting

### ISSUE THREAD

**Issue by tree28** [osxfuse/osxfuse#1015] opened 2024-05-07 14:47 UTC
An observation:

After mounting a volume using version 4.7.1 with the following options 
-o IdentityFile
-o allow_other 
-o defer_permissions 
-o volname
the mounted volume remains mounted but the finder icon vanishes.

Machine configuration: This occurs using Mac OS Sonoma 14.4.1

**Comment by tree28** [comment] 2024-05-07 14:48
Edit:  This occurs using Mac OS Sonoma 14.4.1

**Comment by bfleischer** [comment] 2024-05-07 14:54
Can you post a screenshot? I'm not sure I understand what you mean. 

You are using SSHFS, right?

**Comment by tree28** [comment] 2024-05-07 15:21
> Can you post a screenshot? I'm not sure I understand what you mean.
> 
> You are using SSHFS, right?

Reply - Yes I am using SSHFS 
ie. sudo sshfs user@xx.xx.xx.xx:/remote_path /local_path -o IdentityFile=identity_file_path -o allow_other -o defer_permissions -o volname=myName

I unfortunately cannot post a screen short because there is nothing to see. Typical behavior is that after mounting the drive shows as an icon on my desktop in the finder. Usually the icon is always present, even if the connection drops (this makes sense). Recently the icon flashes up on the desktop when the drive mounts. The icon stays visible for less than a second and then disappears. The drive remains mounted but without an icon which is an inconvenience because I am missing the GUI feedback of knowing the drive is mounted. 

Another observation:

This is not a consistent behavior. It happens intermittently. I do not remember when it started happening but it's fairly recent.

**Comment by bfleischer** [comment] 2024-05-20 10:38
So far I have not been able to reproduce the issue. What happens when you mount the volume without using `sudo`?

**Comment by bfleischer** [comment] 2024-06-11 17:10
Without concrete repro steps or feedback I'm not able to reproduce the issue, so I'm closing the ticket.

**Closed as completed by bfleischer** 2024-06-11 17:10 UTC
Labels: need more info
