### ISSUE TITLE
A moved node retains its old parent directory if its NodeId is reused

### ISSUE THREAD

**Issue by strib** [osxfuse/osxfuse#553] opened 2018-11-06 00:04 UTC
This bug came to my attention because of https://github.com/keybase/kbfs/issues/1881.  In some osxfuse-based file systems (say, mounted at `/mnt/fs`), a user can have this problem:

```bash
cd /mnt/fs
mkdir -p a/b
cd a
mv b ../
cd ../b
touch ../a/c.txt
```

The last line returns an `ENOENT` error.  Drilling down into logs when this happens, it seems like in the path `../a/c.txt`, the `..` component is still being resolved to b's original parent, rather than its new parent, and so of course "a" cannot be found.

It happens this way in KBFS, but it does NOT happen in a simple golang loopback server: https://github.com/keybase/loopback.  After much effort, I tracked the change down to this difference: KBFS reuses its nodes/inodes for the lifetime of the program (at least until the kernel forgets them), while the loopback server creates a new NodeID on each lookup.  (In the bazil.org framework, this results in the node getting a new inode too, since the inode is calculated as a function of the path of the node, and since it moved, it gets a new inode.)

If I modify the loopback server to return the same node each time, as [this branch](https://github.com/keybase/loopback/tree/strib/lookup-old-node) does, I can reproduce the error.

There's a chance this is a problem in the bazil.org/fuse framework, but on inspecting the logs, it seems like the incoming fuse messages that correspond to stat'ing the `..` directory just supply the wrong node ID after the rename happens.

I'm sorry I don't have a good repro in one of the C filesystems, but I couldn't figure out how the loopback system handles lookups.  (I'm very out of practice.)  It should be pretty easy to reproduce.  I've been using osxfuse 3.8.2, on macOS 10.13 to reproduce.  Let me know if you have questions or if something isn't clear!

By the way, this appears to be the same issue as https://www.bountysource.com/issues/53333004-fuse-bug-rename-isn-t-updating-the-parent-of-a-moved-child .

**Comment by bfleischer** [comment] 2018-11-10 11:32
Thank you very much for looking into the issue! It's indeed caused by a bug or non-feature in the FUSE kernel extension. When a file (or a directory) is renamed FUSE does not revoke the vnode. Then when the vnode is reused it points to the wrong parent.  When renaming a file or directory there are two possibilities regarding the lifespan of the corresponding vnode:
    
* The file system server returns a new node ID for the moved file. In this case a new vnode is created and the original vnode will cease to exist. This is what the Go loopback file system is doing. 
    
* The file system server returns the original node ID for the now moved file. In this case the original vnode is reused. This is what KBFS is doing.
    
I've added support for the second possibility by updating the original vnode's parent and name after the rename is completed successfully. The fix will be in version 3.8.3.

**Closed as completed by bfleischer** 2018-11-10 11:32 UTC
Labels: bug
