### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by DarrenPIngram** [osxfuse/osxfuse#1014] opened 2024-05-04 15:38 UTC
Are you, or might you consider, accepting personal donations (however small) for your work which I am using daily?

I did not find an option, but would encourage you to consider it - especially if Github or similar do not make it unviable for you.

**Comment by bfleischer** [comment] 2024-12-06 17:46
Let's give this try. macFUSE is now on GitHub Sponsors. There should be a sponsor button in the top right corner on https://github.com/macfuse.

**Comment by bfleischer** [comment] 2024-12-06 17:47
Duplicate of #910

**Closed as completed by bfleischer** 2024-12-06 17:46 UTC

**Comment by DarrenPIngram** [comment] 2024-12-06 18:01
Seems to work! :)
