### ISSUE TITLE
Kernel extension stuck in loop

### ISSUE THREAD

**Issue by druvissiksalietis** [osxfuse/osxfuse#1038] opened 2024-09-28 17:32 UTC
After each restart I got error:
![Screenshot 2024-09-28 at 20 20 51](https://github.com/user-attachments/assets/d290a9e3-5e51-414b-b5c9-1ef4839b2089)

Always I have this message in Privacy settings:
![Screenshot 2024-09-28 at 20 29 16](https://github.com/user-attachments/assets/aef4bb56-d9d9-4c95-ab56-a2f5f70d7a48)

When I remove macUSE, errors disappear.
When install last version, it again appears.
I tried at leas 5 times restart Mac but still looks like kernel extension can't be installed.

**Comment by druvissiksalietis** [comment] 2024-09-28 17:34
I installed version 4.8.2 and have Mac OS 15.0

**Comment by m23x2** [comment] 2024-10-21 08:48
Same here on the newest Sequoia beta. Any chance for Mac Fuse API soon?

**Comment by bfleischer** [comment] 2024-10-24 09:43
Most likely duplicate of https://github.com/osxfuse/osxfuse/issues/1028.

Please see https://github.com/osxfuse/osxfuse/issues/1028#issuecomment-2434793664.

**Closed as completed by bfleischer** 2024-10-24 09:43 UTC
