### ISSUE TITLE
build error on Mac OS X 10.6 32 bit (with 32 bit kernel) with MacPorts

### ISSUE THREAD

**Issue by dliessi** [osxfuse/osxfuse#321] opened 2016-09-29 08:44 UTC
osxfuse version 3.5.0 with [patch](https://trac.macports.org/browser/trunk/dports/fuse/osxfuse/files/patch-support-mount_osxfuse-mount_osxfuse.c.diff) solving #318 applied.

During `=== BUILD NATIVE TARGET OSXFUSE OF PROJECT OSXFUSE WITH CONFIGURATION Release ===`:
```
2016-09-28 10:48:38.791 dsymutil[11192:607] CFPreferences: user home directory at file://localhost/opt/local/var/macports/home/ is unavailable. User domains will be volatile.
PhaseScriptExecution "BridgeSupport Metadata" build/OSXFUSE.build/Release/OSXFUSE.build/Script-28D525C40EA8076400B7CF7B.sh
    cd /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_fuse_osxfuse/osxfuse/work/osxfuse-osxfuse-cc7d953/framework
    /bin/sh -c /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_fuse_osxfuse/osxfuse/work/osxfuse-osxfuse-cc7d953/framework/build/OSXFUSE.build/Release/OSXFUSE.build/Script-28D525C40EA8076400B7CF7B.sh

2016-09-28 10:48:38.998 sw_vers[11196:40b] CFPreferences: user home directory at file://localhost/opt/local/var/macports/home/ is unavailable. User domains will be volatile.
dyld: Library not loaded: /opt/local/lib/libosxfuse.2.dylib
  Referenced from: /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_fuse_osxfuse/osxfuse/work/framework/OSXFUSE.framework/Versions/A/OSXFUSE
  Reason: image not found
Can't execute compiled C code... aborting
line was: DYLD_FRAMEWORK_PATH="/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_fuse_osxfuse/osxfuse/work/framework" /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_fuse_osxfuse/osxfuse/work/.tmp/bin-0-11195
binary is /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_fuse_osxfuse/osxfuse/work/.tmp/bin-0-11195
Usage: gen_bridge_metadata [options] <headers...>
Use the `-h' flag or consult gen_bridge_metadata(1) for help.
Command /bin/sh failed with exit code 1
Command /bin/sh failed with exit code 1
Touch /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_fuse_osxfuse/osxfuse/work/framework/OSXFUSE.framework
    cd /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_fuse_osxfuse/osxfuse/work/osxfuse-osxfuse-cc7d953/framework
    /usr/bin/touch -c /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_fuse_osxfuse/osxfuse/work/framework/OSXFUSE.framework

Strip /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_fuse_osxfuse/osxfuse/work/framework/OSXFUSE.framework/Versions/A/OSXFUSE
    cd /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_fuse_osxfuse/osxfuse/work/osxfuse-osxfuse-cc7d953/framework
    /Developer/usr/bin/strip -x /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_fuse_osxfuse/osxfuse/work/framework/OSXFUSE.framework/Versions/A/OSXFUSE

** BUILD FAILED **


The following build commands failed:
OSXFUSE:
	PhaseScriptExecution "BridgeSupport Metadata" /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_fuse_osxfuse/osxfuse/work/osxfuse-osxfuse-cc7d953/framework/build/OSXFUSE.build/Release/OSXFUSE.build/Script-28D525C40EA8076400B7CF7B.sh
(1 failure)
```

See [MacPorts ticket](https://trac.macports.org/ticket/52435) and [full build log](https://build.macports.org/builders/ports-10.6_i386_legacy-builder/builds/6852/steps/install-port/logs/stdio).
The same port builds fine on Mac OS X 10.6 64 bit with 32 bit kernel.

**Comment by bfleischer** [comment] 2016-09-30 06:01
I tried to reproduce the issue but installing osxfuse via MacPorts on a Mac OS X 10.6.8 (32 bit) VM with Xcode 3.2.6 works just fine for me.

However I'm able to reproduce the issue using the FUSE build script. The `gen_bridge_metadata` tool seems to be the problem. It tries to run a binary linked against OSXFUSE.framework but since FUSE has not been installed at this point dyld is not able to locate libosxfuse.

To deal with this `DYLD_LIBRARY_PATH` is set when calling `gen_bridge_metadata` but it seems it never reaches dyld. However, on 64 bit hardware there are no issues at all.

**Comment by dliessi** [comment] 2016-09-30 07:23
> I tried to reproduce the issue but installing osxfuse via MacPorts on a Mac OS X 10.6.8 (32 bit) VM with Xcode 3.2.6 works just fine for me.

This is strange: the failing build is on MacPorts' buildbot, which only builds ports.
Do you have anything setup in the VM besides MacPorts that could explain the different behaviour?

**Comment by bfleischer** [comment] 2016-10-04 23:14
The issue should be fixed in https://github.com/osxfuse/framework/commit/ae7d4de10641d5996eaf1943f9bb1483149ef21c. The value of `DYLD_LIBRARY_PATH` was double quoted. This seems to cause issues on Mac OS X 10.6

**Closed by bfleischer** 2016-10-04 23:14 UTC
