### ISSUE TITLE
No remount option

### ISSUE THREAD

**Issue by jhihn** [osxfuse/osxfuse#217] opened 2015-06-22 19:43 UTC
I've been using autofs for a while on Linux laptop. I set up my new mac to use autofs in the same way, but found that the option list isn't nearly as long for OSX. One of these key options is remount, which, when the file system times out, will remount it. This is very cool on my laptop as by the time I get it out of the bag at the coffee shop, it's already to go for me. At the office, my internet cuts out a few times during the day. This usually makes me have to reboot OSX. Below is one such loop (repeats forever). I'm theorizing the lack of a reconnect option along with shoddy internet is breaking things. 

```
Jun 22 15:39:25 Jasons-Mac-mini.local automountd[4846]: = mps_limit 0
Jun 22 15:39:25 Jasons-Mac-mini.local automountd[4846]: automountd running
Jun 22 15:39:25 Jasons-Mac-mini.local automountd[4846]: Can't open /dev/autofs: Resource busy
Jun 22 15:39:25 Jasons-Mac-mini com.apple.xpc.launchd[1] (com.apple.automountd[4846]): Service exited with abnormal code: 2
Jun 22 15:39:25 Jasons-Mac-mini com.apple.xpc.launchd[1] (com.apple.automountd): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Jun 22 15:39:35 Jasons-Mac-mini.local automountd[4847]: = mps_limit 0
Jun 22 15:39:35 Jasons-Mac-mini.local automountd[4847]: automountd running
Jun 22 15:39:35 Jasons-Mac-mini.local automountd[4847]: Can't open /dev/autofs: Resource busy
Jun 22 15:39:35 Jasons-Mac-mini com.apple.xpc.launchd[1] (com.apple.automountd[4847]): Service exited with abnormal code: 2
Jun 22 15:39:35 Jasons-Mac-mini com.apple.xpc.launchd[1] (com.apple.automountd): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Jun 22 15:39:45 Jasons-Mac-mini.local automountd[4849]: = mps_limit 0
Jun 22 15:39:45 Jasons-Mac-mini.local automountd[4849]: automountd running
Jun 22 15:39:45 Jasons-Mac-mini.local automountd[4849]: Can't open /dev/autofs: Resource busy
Jun 22 15:39:45 Jasons-Mac-mini com.apple.xpc.launchd[1] (com.apple.automountd[4849]): Service exited with abnormal code: 2
Jun 22 15:39:45 Jasons-Mac-mini com.apple.xpc.launchd[1] (com.apple.automountd): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
```

**Comment by jhihn** [comment] 2015-06-30 14:40
So I found the remount option, and I'm using it, but my experience is still horrible. 

I use SSHFS on Linux, and it is marvelous and just works. I can walk into a coffee shop and it connects, I can come home and it connects, and is all around fantastic.

My experience with OSX is horrible. In that multiple times a day the mount hangs. I execute a few commands and sometimes it works:
sudo launchctl stop com.apple.autofsd
sudo diskutil unmount force /mnt/ssh/ta

But it usually hangs on the unmount, necessitating reboot.
It is guaranteed though that every morning when I come in I will have to reboot because the mount point is hanging, and those commands don't fix it. I can't say why. I've got the two configs (linux, OSX) as the same as I can (not all options are recognized between the two)

Any pointers in how I can get more resilient performance are appreciated.

**Comment by albertyw** [comment] 2015-10-08 23:03
I was running into the same problem as you, though with not nearly the same frequency.  I've found that `umount -f /your/path` fixes the hanging mounts for me.

**Comment by albertyw** [comment] 2015-10-08 23:04
Also, this seems to be a duplicate of #45

**Comment by torarnv** [comment] 2016-01-12 14:20
> So I found the remount option, and I'm using it, but my experience is still horrible.

@jhihn, where did you find the remount option?

**Comment by jhihn** [comment] 2016-01-13 14:54
I don't have access to that Mac anymore.  I'm sorry.  I think it's just 'remount' in the mount options.  But IIRC,  it doesn't work nearly as well as linux.  I saw still plagued with daily reboots

**Comment by eagle-r** [comment] 2016-01-20 06:16
I'm having a similar issue. I installed yesterday and mounted the remote folder using sshfs with zero issues.

Today when I tried to use it I received a `Device not configured` error. The only way to fix the problem was to use `umount -f` and then remount the volume.

**Closed** 2024-04-05 10:48 UTC
