### ISSUE TITLE
TRESORIT on BIG SUR

### ISSUE THREAD

**Issue by PATPARIS** [osxfuse/osxfuse#800] opened 2021-04-15 19:26 UTC
osxfuse is not yet working on Mac BIG SUR, when will be an update ?

**Comment by bfleischer** [comment] 2021-04-15 19:59
Possibly a duplicate of #780

macFUSE has supported Big Sur from day one. Please raise this issue with the Tresorit team. This is something they need to look into. 

Please know that Tresorit is not contributing to the continued development of the macFUSE software. I asked the Tresorit team for financial support, in order to be able to continue maintaining macFUSE in the future, but they declined. I'm sorry, but I cannot provide support for Tresorit issues.

**Closed as completed by bfleischer** 2021-04-15 19:59 UTC
Labels: question
