### ISSUE TITLE
Interruptible system calls

### ISSUE THREAD

**Issue by kosma** [osxfuse/osxfuse#213] opened 2015-06-12 15:33 UTC
It is impossible to complete any I/O operation under high signal pressure and long latencies.

I've found the problem when trying to `git clone` onto an sshfs-mounted volume; `git` uses `SIGARLM` for progress reporting, and the signal causes the `open()` syscalls to be restarted endlessly. There's also another problem related to sshfs itself: if the `open(O_CREAT|O_EXCL)` call is interrupted after the request is sent to the server, a retry will cause a failure with `EEXISTS` since the file creation is attempted twice (or more, depending on timing).

Attached is a [simple test program](https://gist.github.com/kosma/3383c42d63141a3d9093) which simulates those conditions by causing high signal pressure and trying to create files. The program should be started on an sshfs-mounted volume. Supplying a signal interval comparable to the network lag (about 1000us) will cause a few retries and a "file exists" error; supplying a very small interval will cause the I/O operations to be retried indefinitely.

See [a similar case in Linux](https://www.kernel.org/pub/linux/kernel/people/akpm/patches/2.6/2.6.13/2.6.13-mm2/broken-out/fuse-dont-allow-restarting-of-system-calls.patch) for reference.

**Comment by ukernel** [comment] 2015-07-07 07:36
I'm experiencing the same issue when implementing ceph client for OSX. Is it possible to make osxfuse kext block non-fatal signals when waiting for answers (This is how linux handles this issue) ?

**Comment by bfleischer** [comment] 2015-11-13 14:49
The issue is fixed in osxfuse 3.0.9. Cloning Git repositories on FUSE volumes should work now.

**Closed by bfleischer** 2015-11-13 14:49 UTC

**Comment by kosma** [comment] 2015-11-13 20:02
Much thanks!
