### ISSUE TITLE
Kernel panic with OSXFUSE 3.0.5

### ISSUE THREAD

**Issue by tv42** [osxfuse/osxfuse#232] opened 2015-09-04 22:47 UTC
Running some FUSE tests caused a forced reboot, after the reboot the following panic report appeared. This is a Yosemite box running OSXFUSE 3.0.5.

```
*** Panic Report ***
panic(cpu 0 caller 0xffffff7fac0e828c): "osxfuse: Attempted to lock max-locked recursive lock."@/Users/benjamin/Documents/Projekte/FUSE/Repositories/osxfuse/kext/fuse_locking.c:432
Backtrace (CPU 0), Frame : Return Address
0xffffff802ef53dc0 : 0xffffff802a72ad21 mach_kernel : _panic + 0xd1
0xffffff802ef53e40 : 0xffffff7fac0e828c com.github.osxfuse.filesystems.osxfuse + 33420
0xffffff802ef53e60 : 0xffffff7fac0eb62e com.github.osxfuse.filesystems.osxfuse : _fusefs_stop + 0x314e
0xffffff802ef53eb0 : 0xffffff802a9576ab mach_kernel : _vfs_purge + 0x168b
0xffffff802ef53ed0 : 0xffffff802a941fc4 mach_kernel : _vfs_iterate + 0x1f4
0xffffff802ef53f40 : 0xffffff802a94c177 mach_kernel : _sync + 0x17
0xffffff802ef53f50 : 0xffffff802ac4b376 mach_kernel : _unix_syscall64 + 0x296
0xffffff802ef53fb0 : 0xffffff802a8344a6 mach_kernel : _hndl_unix_scall64 + 0x16
      Kernel Extensions in backtrace:
         com.github.osxfuse.filesystems.osxfuse(3.0.5)[B7B1E3CB-B402-3242-B9D8-328C954FFB22]@0xffffff7fac0e0000->0xffffff7fac0fafff

BSD process name corresponding to current thread: launchd
Boot args: usb=0x800 keepsyms=1 -v -serial=0x1

Mac OS version:
14F27

Kernel version:
Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64
Kernel UUID: 58F06365-45C7-3CA7-B80D-173AFD1A03C4
Kernel slide:     0x000000002a400000
Kernel text base: 0xffffff802a600000
__HIB  text base: 0xffffff802a500000
System model name: MacBook8,1 (VirtualBox)

System uptime in nanoseconds: 18062691081605
last loaded kext at 814204844086: com.github.osxfuse.filesystems.osxfuse	3.0.5 (addr 0xffffff7fac0e0000, size 110592)
last unloaded kext at 78235100914: com.apple.driver.AppleFileSystemDriver	3.0.1 (addr 0xffffff7fac00d000, size 16384)
loaded kexts:
com.github.osxfuse.filesystems.osxfuse	3.0.5
com.apple.filesystems.autofs	3.0
com.apple.iokit.IOBluetoothSerialManager	4.3.6f3
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleUpstreamUserClient	3.6.1
com.apple.driver.AppleMCCSControl	1.2.12
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.driver.AppleLPC	1.7.3
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHWAccess	1
com.apple.driver.AppleHV	1
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleUSBHub	705.4.2
com.apple.driver.XsanFilter	404
com.apple.iokit.IOAHCIBlockStorage	2.7.1
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	36
com.apple.driver.AppleUSBOHCI	656.4.1
com.apple.driver.AppleAHCIPort	3.1.2
com.apple.driver.AppleIntel8254XEthernet	3.1.4b1
com.apple.driver.AppleACPIButtons	3.1
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	161
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.kext.triggers	1.0
com.apple.iokit.IOSerialFamily	11
com.apple.driver.AppleSMBusController	1.0.13d1
com.apple.iokit.IOSMBusFamily	1.1
com.apple.iokit.IOUSBUserClient	705.4.0
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.driver.IOPlatformPluginFamily	5.9.1d7
com.apple.iokit.IOSurface	97.4
com.apple.iokit.IOBluetoothFamily	4.3.6f3
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.iokit.IONDRVSupport	2.4.1
com.apple.iokit.IOGraphicsFamily	2.4.1
com.apple.iokit.IOUSBHIDDriver	705.4.0
com.apple.driver.AppleUSBComposite	705.4.9
com.apple.iokit.IOSCSIMultimediaCommandsDevice	3.7.5
com.apple.iokit.IOBDStorageFamily	1.7
com.apple.iokit.IODVDStorageFamily	1.7.1
com.apple.iokit.IOCDStorageFamily	1.7.1
com.apple.iokit.IOAHCISerialATAPI	2.6.1
com.apple.iokit.IOSCSIArchitectureModelFamily	3.7.5
com.apple.driver.AppleEFINVRAM	2.0
com.apple.iokit.IOUSBFamily	720.4.4
com.apple.iokit.IOAHCIFamily	2.7.5
com.apple.iokit.IONetworkingFamily	3.2
com.apple.driver.AppleEFIRuntime	2.0
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.DiskImages	398
com.apple.iokit.IOStorageFamily	2.0
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	3.1
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.corecrypto	1.0
com.apple.kec.Libm	1
com.apple.kec.pthread	1
Model: MacBook8,1, BootROM VirtualBox, 1 processor, 1.1 GHz, 2 GB, SMC 2.3f35
Graphics: Display, PCI, 3 MB
Memory Module: Bank 0/DIMM 0, 2 GB, DRAM, 1600 MHz, innotek GmbH, -
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: VBOX HARDDISK, 21.47 GB
Serial ATA Device: VBOX CD-ROM
USB Device: USB Tablet
USB Device: USB Keyboard
Thunderbolt Bus: 
```

**Comment by bfleischer** [comment] 2015-09-04 23:26
Can you provide some more context? What exactly were you doing when this happened? It looks like the  panic happened when unloading the osxfuse kernel extension. Are you able to reproduce the crash?

**Comment by tv42** [comment] 2015-09-04 23:36
There should have been no unloading, though unmounting definitely. It was running a series of test that mount a filesystem, perform operations, unmount; as the machine rebooted while I wasn't looking at it, I don't have much more than that. This is just the first time OS X has offered a panic report to me, so I thought I should save it. I'll see if I get more panic reports; I can reproduce *a* crash just by busy looping on mount+operations+unmount, but I don't know if that's the same crash.

**Comment by tv42** [comment] 2015-09-05 00:10
Oh, one more thing pops to mind: this might be related to the userspace process having a locking bug that causes a time out in the 3.0.5 new getattr call done from inside cache invalidation.

**Comment by bfleischer** [comment] 2015-09-07 20:19
This is the symbolicated stack trace:

```
panic
fusefs_recursive_lock_lock (in osxfuse) (fuse_locking.c:434)
fuse_vfsop_biglock_sync (in osxfuse) (fuse_vfsops.c:1508)
vfs_purge
vfs_iterate
sync
unix_syscall64
hndl_unix_scall64
```

The crash has nothing to do with unloading the osxfuse kernel extension. `_fusefs_stop ` in the unsymbolicated crash log set me on the wrong track.

Are you using the sync(2) syscall in your file system implementation?

**Comment by tv42** [comment] 2015-09-07 21:43
Both the tests call fsync on files in the FUSE mount, and the FUSE backend uses a database library which calls fsync on its files (stored on the actual filesystem). I don't think there's a bare sync, but fsyncs both ways most definitely.

**Comment by bfleischer** [comment] 2015-09-07 22:25
Could you check if you can reproduce the crash with the following build?

https://www.dropbox.com/s/igqezbxn9psnduw/osxfuse-3.0.5.dmg?dl=0

Please make sure to uninstall osxfuse (and unload the osxfuse kernel extension) before installing the new build.

**Comment by tv42** [comment] 2015-09-08 17:55
That build hasn't crashed yet, with the same workload as earlier. I'll keep it running for a few hours more, but looks promising. And then I'll push it harder ;)

**Comment by tv42** [comment] 2015-09-08 21:09
I've had this on a loop for most of today, and have not seen a crash/hang from a workload that used to trigger those every 10-30 minutes.

**Comment by bfleischer** [comment] 2015-09-08 21:21
Thanks for the feedback. I think we can close the issue. The fix will be in the next release.

**Closed by bfleischer** 2015-09-08 21:21 UTC

**Comment by alonre** [comment] 2016-10-27 20:56
Hey guys,
We still randomly encounter this with FUSE 3.5.2 on macOS 10.12.
We saw the same thing about 18 months ago on a previous attempt to support Spotlight indexing on our Virtual FS.

```
Tue Oct 25 12:15:09 2016

*** Panic Report ***
panic(cpu 4 caller 0xffffff7f9d2aca2f): "osxfuse: Attempted to lock max-locked recursive lock."@/Users/benjamin/Documents/Projekte/FUSE/Repositories/osxfuse/kext/osxfuse/fuse_locking.c:432
Backtrace (CPU 4), Frame : Return Address
0xffffff922ae3b380 : 0xffffff8019cf748c 
0xffffff922ae3b400 : 0xffffff7f9d2aca2f 
0xffffff922ae3b420 : 0xffffff7f9d2b28ba 
0xffffff922ae3b440 : 0xffffff801a201d0d 
0xffffff922ae3b530 : 0xffffff8019d61108 
0xffffff922ae3b580 : 0xffffff8019d60e93 
0xffffff922ae3b5c0 : 0xffffff8019d6fd13 
0xffffff922ae3b6f0 : 0xffffff8019d749e4 
0xffffff922ae3b8d0 : 0xffffff8019e098da 
0xffffff922ae3bab0 : 0xffffff8019ca9743 
0xffffff922ae3bad0 : 0xffffff8019ca684b 
0xffffff922ae3bc30 : 0xffffff801a18dc44 
0xffffff922ae3bc70 : 0xffffff7f9d2ba048 
0xffffff922ae3bd30 : 0xffffff7f9d2b3134 
0xffffff922ae3bd60 : 0xffffff8019f53fe0 
0xffffff922ae3bde0 : 0xffffff8019f4570e 
0xffffff922ae3be50 : 0xffffff801a1a3927 
0xffffff922ae3bef0 : 0xffffff801a1a3ba2 
0xffffff922ae3bf50 : 0xffffff801a22a366 
0xffffff922ae3bfb0 : 0xffffff8019ca9f46 
      Kernel Extensions in backtrace:
         com.github.osxfuse.filesystems.osxfuse(3.5.2)[FAD7BE87-C14C-345F-A049-8689D1F080A0]@0xffffff7f9d2ab000->0xffffff7f9d2c3fff

BSD process name corresponding to current thread: mds_stores

Mac OS version:
16A323

Kernel version:
Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64
Kernel UUID: 622D2470-C34D-31F9-A62B-6AA9A3C6A3CD
Kernel slide:     0x0000000019a00000
Kernel text base: 0xffffff8019c00000
__HIB  text base: 0xffffff8019b00000
System model name: MacBookPro11,3 (Mac-2BD1B31983FE1663)

System uptime in nanoseconds: 190506610788775
last loaded kext at 183690286028621: com.getdropbox.dropbox.kext	1.8.1 (addr 0xffffff7f9d2c4000, size 49152)
last unloaded kext at 183689454059256: com.getdropbox.dropbox.kext	1.8.1 (addr 0xffffff7f9d2c4000, size 24576)
loaded kexts:
com.getdropbox.dropbox.kext	1.8.1
com.github.osxfuse.filesystems.osxfuse	3.5.2
com.vmware.kext.vmioplug.15.1.7	15.1.7
com.vmware.kext.vmx86	0377.10.13
com.vmware.kext.vmnet	0377.10.13
com.vmware.kext.vsockets	90.8.0
com.vmware.kext.vmci	90.8.1
org.virtualbox.kext.VBoxNetAdp	5.0.26
org.virtualbox.kext.VBoxNetFlt	5.0.26
org.virtualbox.kext.VBoxUSB	5.0.26
org.virtualbox.kext.VBoxDrv	5.0.26
com.apple.filesystems.smbfs	3.1
com.apple.driver.AppleHWSensor	1.9.5d0
com.apple.driver.AudioAUUC	1.70
com.apple.filesystems.autofs	3.0
com.apple.driver.AGPM	110.23.7
com.apple.driver.ApplePlatformEnabler	2.7.0d0
com.apple.driver.X86PlatformShim	1.0.0
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleGraphicsDevicePolicy	3.13.60
com.apple.driver.AppleHDA	276.26
com.apple.driver.AppleUpstreamUserClient	3.6.4
com.apple.GeForce	10.1.2
com.apple.driver.AppleSMCLMU	208
com.apple.driver.AppleIntelHD5000Graphics	10.1.8
com.apple.driver.AppleMCCSControl	1.2.13
com.apple.driver.AppleCameraInterface	5.57.0
com.apple.driver.AppleMuxControl	3.13.60
com.apple.driver.AppleIntelFramebufferAzul	10.1.8
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	5.0.0f18
com.apple.driver.pmtelemetry	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOBluetoothSerialManager	5.0.0f18
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHV	1
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleLPC	3.1
com.apple.driver.AppleThunderboltIP	3.0.8
com.apple.driver.AppleUSBCardReader	404.1.1
com.apple.driver.AppleUSBTCButtons	251
com.apple.driver.AppleUSBTCKeyboard	251
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	39
com.apple.filesystems.hfs.kext	366.1.1
com.apple.iokit.IOAHCIBlockStorage	295.1.1
com.apple.driver.AppleAHCIPort	326
com.apple.driver.AirPort.Brcm4360	1100.37.1a16
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleACPIButtons	5.0
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	5.0
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	171
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleBluetoothHIDKeyboard	197
com.apple.driver.AppleHIDKeyboard	197
com.apple.driver.IOBluetoothHIDDriver	5.0.0f18
com.apple.iokit.IOUSBUserClient	900.4.1
com.apple.kext.triggers	1.0
com.apple.driver.DspFuncLib	276.26
com.apple.kext.OSvKernDSPLib	525
com.apple.nvidia.driver.NVDAGK100Hal	10.1.2
com.apple.nvidia.driver.NVDAResman	10.1.2
com.apple.driver.AppleSMBusController	1.0.14d1
com.apple.driver.AppleHDAController	276.26
com.apple.iokit.IOHDAFamily	276.26
com.apple.iokit.IOAudioFamily	205.11
com.apple.vecLib.kext	1.2.0
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IONDRVSupport	2.4.1
com.apple.driver.AppleGraphicsControl	3.13.60
com.apple.AppleGraphicsDeviceControl	3.13.60
com.apple.iokit.IOAcceleratorFamily2	288.13
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.iokit.IOBluetoothHostControllerUSBTransport	5.0.0f18
com.apple.iokit.IOBluetoothHostControllerTransport	5.0.0f18
com.apple.iokit.IOSurface	152
com.apple.iokit.IOGraphicsFamily	2.4.1
com.apple.iokit.IOSerialFamily	11
com.apple.iokit.IOBluetoothFamily	5.0.0f18
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.iokit.IOSCSIBlockCommandsDevice	394
com.apple.iokit.IOUSBMassStorageDriver	131.1.1
com.apple.iokit.IOSCSIArchitectureModelFamily	394
com.apple.driver.AppleUSBMultitouch	258
com.apple.driver.usb.IOUSBHostHIDDevice	1.1
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.1
com.apple.driver.usb.AppleUSBHub	1.1
com.apple.driver.CoreStorage	540
com.apple.filesystems.hfs.encodings.kext	1
com.apple.iokit.IOAHCIFamily	288
com.apple.driver.AppleThunderboltDPInAdapter	4.5.3
com.apple.driver.AppleThunderboltDPAdapterFamily	4.5.3
com.apple.driver.AppleThunderboltPCIDownAdapter	2.0.3
com.apple.driver.AppleThunderboltNHI	4.1.3
com.apple.iokit.IOThunderboltFamily	6.2.1
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.2
com.apple.driver.corecapture	1.0.4
com.apple.driver.usb.AppleUSBXHCIPCI	1.1
com.apple.driver.usb.AppleUSBXHCI	1.1
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.iokit.IOUSBHostFamily	1.1
com.apple.driver.AppleUSBHostMergeProperties	1.1
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleBusPowerController	1.0
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.driver.AppleEFIRuntime	2.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.DiskImages	444
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	5.0
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.Libm	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0
```

**Comment by alonre** [comment] 2016-10-27 20:57
The previous report (Fuse 2.8 on 10.10):
```console
Anonymous UUID:       5A5A6CA0-3F30-5DA3-4A1B-E1CFF0AADD8B

Mon Aug 10 20:15:07 2015

*** Panic Report ***
panic(cpu 2 caller 0xffffff7f9c563769): "OSXFUSE: Attempted to lock max-locked recursive lock."@/Users/ali/git/apps/Mac/osxfuse/kext/fuse_locking.c:436
Backtrace (CPU 2), Frame : Return Address
0xffffff81475332c0 : 0xffffff8019d2ad21 
0xffffff8147533340 : 0xffffff7f9c563769 
0xffffff8147533360 : 0xffffff7f9c56da78 
0xffffff8147533380 : 0xffffff801a243dff 
0xffffff8147533490 : 0xffffff8019d8a018 
0xffffff81475334e0 : 0xffffff8019d89163 
0xffffff8147533520 : 0xffffff8019d946ab 
0xffffff81475336d0 : 0xffffff8019d98ba3 
0xffffff81475338e0 : 0xffffff8019e169a8 
0xffffff8147533aa0 : 0xffffff8019e33ca3 
0xffffff8147533ac0 : 0xffffff8019e102c1 
0xffffff8147533c20 : 0xffffff801a1da2f9 
0xffffff8147533c60 : 0xffffff7f9c56cd40 
0xffffff8147533d20 : 0xffffff7f9c56e2be 
0xffffff8147533d50 : 0xffffff8019f6e770 
0xffffff8147533dd0 : 0xffffff8019f63ccf 
0xffffff8147533e40 : 0xffffff801a1ec1a5 
0xffffff8147533ef0 : 0xffffff801a1ec408 
0xffffff8147533f50 : 0xffffff801a24b376 
0xffffff8147533fb0 : 0xffffff8019e344a6 
      Kernel Extensions in backtrace:
         com.github.osxfuse.filesystems.osxfusefs(2.8)[E015A889-EFFC-34A8-A1A3-61FB282233DD]@0xffffff7f9c55d000->0xffffff7f9c572fff

BSD process name corresponding to current thread: mds_stores

Mac OS version:
14F25a

Kernel version:
Darwin Kernel Version 14.5.0: Mon Aug  3 19:52:24 PDT 2015; root:xnu-2782.40.9~4/RELEASE_X86_64
Kernel UUID: 11ED5108-EE6B-3710-A9EB-6B1DF45CD161
Kernel slide:     0x0000000019a00000
Kernel text base: 0xffffff8019c00000
__HIB  text base: 0xffffff8019b00000
System model name: MacBookPro11,1 (Mac-189A3D4F975D5FFC)

System uptime in nanoseconds: 85535604225283
last loaded kext at 74578444111501: com.Logitech.Control Center.HID Driver	3.9.1 (addr 0xffffff7f9c5a0000, size 286720)
last unloaded kext at 74532868948632: com.Logitech.Control Center.HID Driver	3.9.1 (addr 0xffffff7f9c5a0000, size 286720)
loaded kexts:
com.Logitech.Control Center.HID Driver	3.9.1
com.vmware.kext.vmioplug.12.1.19	12.1.19
com.vmware.kext.vmx86	0268.43.43
com.vmware.kext.vmnet	0268.43.43
com.vmware.kext.vsockets	90.5.7
com.vmware.kext.vmci	90.5.7
com.github.osxfuse.filesystems.osxfusefs	2.8.0
com.intel.kext.intelhaxm	1.1.1
com.apple.filesystems.smbfs	3.0.2
com.apple.filesystems.autofs	3.0
com.apple.driver.AudioAUUC	1.70
com.apple.iokit.IOBluetoothSerialManager	4.3.6f3
com.apple.driver.ApplePlatformEnabler	2.2.0d4
com.apple.driver.AGPM	110.19.6
com.apple.driver.X86PlatformShim	1.0.0
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleUpstreamUserClient	3.6.1
com.apple.driver.AppleHDA	272.18.1
com.apple.driver.AppleThunderboltIP	2.0.2
com.apple.driver.AppleSMCLMU	2.0.7d0
com.apple.driver.AppleLPC	1.7.3
com.apple.driver.AppleCameraInterface	5.36.0
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHWAccess	1
com.apple.driver.AppleHV	1
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	4.3.6f3
com.apple.driver.AppleIntelHD5000Graphics	10.0.6
com.apple.driver.AppleIntelFramebufferAzul	10.0.6
com.apple.driver.AppleBacklight	170.7.4
com.apple.driver.AppleMCCSControl	1.2.12
com.apple.driver.AppleUSBCardReader	3.5.5
com.apple.driver.AppleUSBTCButtons	240.2
com.apple.driver.AppleUSBTCKeyboard	240.2
com.apple.driver.AppleUSBHub	705.4.2
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	36
com.apple.driver.XsanFilter	404
com.apple.iokit.IOAHCIBlockStorage	2.7.1
com.apple.driver.AppleAHCIPort	3.1.2
com.apple.driver.AirPort.Brcm4360	930.37.3
com.apple.driver.AppleUSBXHCI	710.4.11
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleACPIButtons	3.1
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	3.1
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	161
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleBluetoothHIDKeyboard	176.2
com.apple.driver.AppleHIDKeyboard	176.2
com.apple.driver.IOBluetoothHIDDriver	4.3.6f3
com.apple.kext.triggers	1.0
com.apple.driver.DspFuncLib	272.18.1
com.apple.kext.OSvKernDSPLib	1.15
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.IOPlatformPluginFamily	5.9.1d7
com.apple.iokit.IOSerialFamily	11
com.apple.iokit.IOUSBUserClient	705.4.0
com.apple.driver.AppleHDAController	272.18.1
com.apple.iokit.IOHDAFamily	272.18.1
com.apple.iokit.IOAudioFamily	203.3
com.apple.vecLib.kext	1.2.0
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.iokit.IOBluetoothHostControllerUSBTransport	4.3.6f3
com.apple.iokit.IOSurface	97.4
com.apple.AppleGraphicsDeviceControl	3.10.25
com.apple.iokit.IOAcceleratorFamily2	156.16
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IONDRVSupport	2.4.1
com.apple.driver.AppleSMBusController	1.0.13d1
com.apple.iokit.IOGraphicsFamily	2.4.1
com.apple.iokit.IOSCSIBlockCommandsDevice	3.7.5
com.apple.iokit.IOUSBMassStorageClass	3.7.2
com.apple.iokit.IOSCSIArchitectureModelFamily	3.7.5
com.apple.driver.AppleUSBMultitouch	245.2
com.apple.iokit.IOBluetoothFamily	4.3.6f3
com.apple.iokit.IOUSBHIDDriver	705.4.0
com.apple.driver.AppleUSBMergeNub	705.4.0
com.apple.driver.AppleUSBComposite	705.4.9
com.apple.driver.CoreStorage	471.30.1
com.apple.iokit.IOAHCIFamily	2.7.5
com.apple.driver.AppleThunderboltDPInAdapter	4.0.6
com.apple.driver.AppleThunderboltDPAdapterFamily	4.0.6
com.apple.driver.AppleThunderboltPCIDownAdapter	2.0.2
com.apple.driver.AppleThunderboltNHI	3.1.7
com.apple.iokit.IOThunderboltFamily	4.2.2
com.apple.iokit.IO80211Family	730.60
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.2
com.apple.iokit.IOUSBFamily	720.4.4
com.apple.driver.AppleEFINVRAM	2.0
com.apple.driver.AppleEFIRuntime	2.0
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.DiskImages	398
com.apple.iokit.IOStorageFamily	2.0
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	3.1
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.Libm	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0
 ```

**Comment by bfleischer** [comment] 2016-10-27 21:28
Thanks @alonre for the bug report. I will look into the first panic. The osxfuse version in the second panic is not an official release. This means the panic log is pretty much useless unless you still have the corresponding debug symbols.

**Comment by alonre** [comment] 2016-10-27 21:38
You're right, sorry about that. I do not have those debug symbols.

Another clue I can provide is that **the panic occurred when I woke the machine up** after it has been asleep for a short while.
Indexing was enabled on the volume at the time (was turned on ~1h earlier).

Thanks again for looking into this.

**Comment by bfleischer** [comment] 2016-10-27 22:20
It looks like this is a different issue from the one @tv42 reported. But it should be easy to fix.

Symbolicated first stack trace:

```
panic(cpu 4 caller 0xffffff7f9d2aca2f): "osxfuse: Attempted to lock max-locked recursive lock."@/Users/benjamin/Documents/Projekte/FUSE/Repositories/osxfuse/kext/osxfuse/fuse_locking.c:432
Backtrace (CPU 4), Frame : Return Address
0xffffff922ae3b380 : 0xffffff8019cf748c 
0xffffff922ae3b400 : 0xffffff7f9d2aca2f fusefs_recursive_lock_lock (in osxfuse) (fuse_locking.c:434)
0xffffff922ae3b420 : 0xffffff7f9d2b28ba fuse_biglock_vnop_pagein (in osxfuse) (fuse_biglock_vnops.c:420)
0xffffff922ae3b440 : 0xffffff801a201d0d vnode_pagein (in kernel) (kpi_vfs.c:5165)
0xffffff922ae3b530 : 0xffffff8019d61108 vnode_pager_cluster_read (in kernel) (bsd_vm.c:877)
0xffffff922ae3b580 : 0xffffff8019d60e93 vnode_pager_data_request (in kernel) (bsd_vm.c:645)
0xffffff922ae3b5c0 : 0xffffff8019d6fd13 vm_fault_page (in kernel) (memory_object.c:2228)
0xffffff922ae3b6f0 : 0xffffff8019d749e4 vm_fault_internal (in kernel) (vm_fault.c:4686)
0xffffff922ae3b8d0 : 0xffffff8019e098da kernel_trap (in kernel) (vm_fault.c:3397)
0xffffff922ae3bab0 : 0xffffff8019ca9743 trap_from_kernel (in kernel) + 38
0xffffff922ae3bad0 : 0xffffff8019ca684b _bcopy (in kernel) + 11
0xffffff922ae3bc30 : 0xffffff801a18dc44 uiomove64 (in kernel) (kern_subr.c:181)
0xffffff922ae3bc70 : 0xffffff7f9d2ba048 fuse_vnop_write (in osxfuse) (fuse_vnops.c:3899)
0xffffff922ae3bd30 : 0xffffff7f9d2b3134 fuse_biglock_vnop_write (in osxfuse) (fuse_biglock_vnops.c:727)
0xffffff922ae3bd60 : 0xffffff8019f53fe0 VNOP_WRITE (in kernel) (kpi_vfs.c:3408)
0xffffff922ae3bde0 : 0xffffff8019f4570e vn_write (in kernel) (vfs_vnops.c:1150)
0xffffff922ae3be50 : 0xffffff801a1a3927 dofilewrite (in kernel) (kern_descrip.c:5781)
0xffffff922ae3bef0 : 0xffffff801a1a3ba2 pwrite_nocancel (in kernel) (sys_generic.c:551)
0xffffff922ae3bf50 : 0xffffff801a22a366 unix_syscall64 (in kernel) (systemcalls.c:376)
0xffffff922ae3bfb0 : 0xffffff8019ca9f46 hndl_unix_scall64 (in kernel) + 22
      Kernel Extensions in backtrace:
         com.github.osxfuse.filesystems.osxfuse(3.5.2)[FAD7BE87-C14C-345F-A049-8689D1F080A0]@0xffffff7f9d2ab000->0xffffff7f9d2c3fff
```
