### ISSUE TITLE
direct_io option is not available in 3.5.2

### ISSUE THREAD

**Issue by cypromis** [osxfuse/osxfuse#323] opened 2016-10-07 12:17 UTC
I am trying to mount a filesystem with osxfuse 3.5.2 and get:
fuse: unknown option `direct_io'
error in fuse_lowlevel_new

when specifying -o direct_io

tried directio, DirectIO as well but neither works.

**Comment by oneill1979** [comment] 2016-10-09 19:55
Try "-odirect_io".

**Comment by cypromis** [comment] 2016-10-09 21:48
same

**Comment by alecw645** [comment] 2016-10-14 01:42
same, I cant mount either of my external hardrives!  Does anyone have a fix for this?

**Comment by bfleischer** [comment] 2016-10-14 06:05
The `direct_io` option is not available when using the low-level FUSE interface. However, it works fine when using the the high-level FUSE interface. This is not a bug in 3.5.2. It had always been like that.

**Closed** 2016-10-17 20:56 UTC
