### ISSUE TITLE
All files report as writable

### ISSUE THREAD

**Issue by bigphatjan** [osxfuse/osxfuse#357] opened 2017-02-03 18:35 UTC
Hello!

Using OSXFUSE version 3.5.4_0 installed using macports on MacOS Sierra, all files are reported as writable even if they are not. Permissions show correctly, and permission is denied if I try to write to the file. E.g.:

**$** ls -l not_writable
```
-r--r--r--  1 user  group  0 Feb  3 13:30 not_writable
```

**$** [ -w not_writable ] && echo "Writable!"
```
Writable!
```

**$** echo test > not_writable
```
-bash: not_writable: Permission denied
```

**Comment by bigphatjan** [comment] 2017-02-03 18:46
It seems that adding -o default_permissions to the mount options fixes this behavior.

I'll leave this open anyway in case it is possible to fix when using the default mount options.

**Comment by bfleischer** [comment] 2017-04-14 20:59
Which file system are you using? I'm unable to reproduce the issue with loopback (reference file system).

**Comment by bigphatjan** [comment] 2017-04-14 21:25
Hi Benjamin, the mounted filesystem is ext4 served from a CentOS 6.8 system.

Perhaps I posted to the wrong issue tracker and certainly I should have been clearer that this behavior occurs when using sshfs.

**Comment by bfleischer** [comment] 2017-07-06 20:12
Sorry for the long wait. I finally found some time to look into this some more.

With `default_permissions` the kernel will attempt to do the "right thing" based on what it can "see" (the permission bits as reported by the file system). 

So with `default_permissions` your `[ -w not_writable ]` test will evaluate to false: Based on the permission bits macOS will correctly return false.

Without `default_permissions` the test is passed to sshfs, which seems to return true, even though the file is obviously not writeable. I'm not sure why this is the case but it is most likely SSH related. It could be a configuration issue on the server.

I don't think this can be "fixed" on the FUSE level, so I'm going to close the issue.

**Closed by bfleischer** 2017-07-06 20:12 UTC
