### ISSUE TITLE
exchangedata fails with ENOENT if one of the files is recently moved to different directory

### ISSUE THREAD

**Issue by sarat-ravi** [osxfuse/osxfuse#409] opened 2017-08-28 21:29 UTC
# Overview
`exchangedata` fails with ENOENT if one of the files is recently moved to different directory, because the path of the recently renamed file according to the fuse userspace library is incorrect. More specifically, the path of the recently renamed file is composed of the file's *old* parent (before the rename), with the file's *new* name.

Upon digging further into the fuse kext, it appears that the parent of the `vnode_t vp` representing the file is still the old parent, despite the rename already finishing successfully.

# Steps to reproduce
- Install osxfuse (3.6.3) (tested on OSX 10.11.6)
- Mount filesystem to `/Volumes/loop` (Used [LoopbackFS](https://github.com/osxfuse/filesystems/tree/38c9df4b8e575f403cb5f8ecfe6b1d36250ecbbc/filesystems-objc/LoopbackFS)
- Run the following c code: 
```C
#include <sys/stat.h>
#include <errno.h>
#include <string.h>
#include <stdio.h>

#include <unistd.h>
#include <sys/attr.h>

/**
 * Usage:
 * ------------------------------------------
 *  1) Run LoopbackFS and mount to /Volumes/loop (which is the default for LoopbackFS obj-c example)
 *  2) Run this binary (i.e. gcc exchangetest.c -o exchangetest).
 * ------------------------------------------
 */
int main(int c, char** args) {
    printf("running exchange test\n");
    int err = 0;

    char* dir1 = "/Volumes/loop/dir1";
    char* path1 = "/Volumes/loop/file1";
    char* path2 = "/Volumes/loop/file2";
    char* newpath1 = "/Volumes/loop/dir1/newpath1";

    // Create files and write data.
    FILE* f1 = fopen(path1, "wb");
    fputs("file1data", f1);
    fclose(f1);

    FILE* f2 = fopen(path2, "wb");
    fputs("file2data", f2);
    fclose(f2);

    // Create a folder and move file1 to this new folder.
    err = mkdir(dir1, S_IRWXU | S_IRWXG | S_IRWXO);
    if (err && errno != EEXIST) {
        printf("unable to mkdir %s: %s\n", dir1, strerror(errno));
        return err;
    }

    err = rename(path1, newpath1);
    if (err) {
        printf("unable to rename %s to %s: %s\n", path1, newpath1, strerror(errno));
        return err;
    }

    // Observe that exchangedata fails with "No such file or directory", which is a bug.
    err = exchangedata(newpath1, path2, 0);
    if (err) {
        printf("unable to exchange data between %s to %s: %s\n", newpath1, path2, strerror(errno));
        return err;
    }

    printf("done\n");
    return 0;
}
```

# Observations

## kext
At the end of renaming a file, the parent is unchanged, even though the file is moved to a different directory:

```C
FUSE_VNOP_EXPORT
int
fuse_vnop_rename(struct vnop_rename_args *ap)
{
    vnode_t fdvp               = ap->a_fdvp;
    vnode_t fvp                = ap->a_fvp;
    struct componentname *fcnp = ap->a_fcnp;
    vnode_t tdvp               = ap->a_tdvp;
    vnode_t tvp                = ap->a_tvp;
    struct componentname *tcnp = ap->a_tcnp;
    vfs_context_t context      = ap->a_context;

    int err = 0;

    fuse_trace_printf_vnop_novp();

    if (fuse_isdeadfs_fs(fdvp)) {
        return ENXIO;
    }

    CHECK_BLANKET_DENIAL(fdvp, context, ENOENT);

    fuse_vncache_purge(fvp);

    err = fuse_internal_rename(fdvp, fvp, fcnp, tdvp, tvp, tcnp, ap->a_context);

    if (err == 0) {
        fuse_invalidate_attr(fdvp);
        if (tdvp != fdvp) {
            fuse_invalidate_attr(tdvp);
        }
    }

    if (tvp != NULLVP) {
        if (tvp != fvp) {
            fuse_vncache_purge(tvp);
        }
        if (err == 0) {

            /*
             * If we want the file to just "disappear" from the standpoint
             * of those who might have it open, we can do a revoke/recycle
             * here. Otherwise, don't do anything. Only doing a recycle will
             * make our fufh-checking code in reclaim unhappy, leading us to
             * proactively panic.
             */

            /*
             * 1. revoke
             * 2. recycle
             */
        }
    }

    if (vnode_isdir(fvp)) {
        if ((tvp != NULLVP) && vnode_isdir(tvp)) {
            fuse_vncache_purge(tdvp);
        }
        fuse_vncache_purge(fdvp);
    }

    // -------------------> get_parent(vp) == fdvp at this point.
    return err;
}
```
Meanwhile, after the the rename finishes and exchangedata is called, the following code runs where the parent is incorrect:

```C
__private_extern__
int
fuse_internal_exchange(vnode_t       fvp,
                       const char   *fname,
                       size_t        flen,
                       vnode_t       tvp,
                       const char   *tname,
                       size_t        tlen,
                       int           options,
                       vfs_context_t context)
{
    struct fuse_data *data;
    struct fuse_dispatcher fdi;
    struct fuse_abi_data fei;
    struct fuse_vnode_data *ffud = VTOFUD(fvp);
    struct fuse_vnode_data *tfud = VTOFUD(tvp);
    vnode_t fdvp = ffud->parentvp; // -------------------> fdvp is still the old parent!!
    vnode_t tdvp = tfud->parentvp;
    void *next;
    int err = 0;

    data = fuse_get_mpdata(vnode_mount(fvp));

    fdata_wait_init(data);
    fdisp_init(&fdi, fuse_exchange_in_sizeof(DATOI(data)) + flen + tlen + 2);
    fdisp_make_vp(&fdi, FUSE_EXCHANGE, fvp, context);
    fuse_abi_data_init(&fei, DATOI(data), fdi.indata);

    fuse_exchange_in_set_olddir(&fei, VTOI(fdvp));
    fuse_exchange_in_set_newdir(&fei, VTOI(tdvp));
    fuse_exchange_in_set_options(&fei, (uint64_t)options);

    next = (char *)fdi.indata + fuse_exchange_in_sizeof(DATOI(data));

    memcpy(next, fname, flen);
    ((char *)next)[flen] = '\0';

    memcpy((char *)next + flen + 1, tname, tlen);
    ((char *)next)[flen + tlen + 1] = '\0';

#if M_OSXFUSE_ENABLE_BIG_LOCK
    fuse_biglock_unlock(data->biglock);
#endif
    ubc_msync(fvp, (off_t)0, (off_t)ffud->filesize, NULL,
              UBC_PUSHALL | UBC_INVALIDATE | UBC_SYNC);
    ubc_msync(tvp, (off_t)0, (off_t)tfud->filesize, NULL,
              UBC_PUSHALL | UBC_INVALIDATE | UBC_SYNC);
#if M_OSXFUSE_ENABLE_BIG_LOCK
    fuse_biglock_lock(data->biglock);
#endif

    err = fdisp_wait_answ(&fdi);
   
...

    return err;
}
```

## User-space filesystem (LoopbackFS)

```objc
- (BOOL)exchangeDataOfItemAtPath:(NSString *)path1
                  withItemAtPath:(NSString *)path2
                           error:(NSError **)error {
  // path1 is incorrect, as it is composed of the old path before the rename, but with the new filename after the rename.
  NSString* p1 = [rootPath_ stringByAppendingString:path1];
  NSString* p2 = [rootPath_ stringByAppendingString:path2];
  int ret = exchangedata([p1 UTF8String], [p2 UTF8String], 0);
  if ( ret < 0 ) {
    if ( error ) {
      *error = [NSError errorWithPOSIXCode:errno];
    }
    return NO;
  }
  return YES;
}
```

**Comment by kaushiks** [comment] 2018-03-14 23:43
> // -------------------> get_parent(vp) == fdvp at this point.

This I believe is also what leads to the issue I'd reported earlier: https://github.com/osxfuse/osxfuse/issues/466.

@sarattall How are you guys working around this bug?

**Comment by kainjow** [comment] 2019-04-29 23:38
@bfleischer any update on a possible fix for this?

**Comment by bfleischer** [comment] 2019-05-01 16:16
@kainjow The rename issue should be fixed in version 3.8.3. Did you test with 3.8.3?

**Comment by bfleischer** [comment] 2019-05-01 16:47
Scratch my previous comment. I'm able to reproduce the issue with the latest version of FUSE.

**Comment by kaushiks** [comment] 2019-05-01 17:24
@bfleischer @kainjow The rename issue is mostly fixed. Please see https://github.com/osxfuse/kext/pull/12 for a fix to an issue we ran into in our testing.

**Comment by bfleischer** [comment] 2019-05-01 17:25
Ok, after performing some more tests I can confirm that the fix to #466 in version 3.8.3 fixed the original issue @sarat-ravi described. When running @sarat-ravi test application on 10.13 and 10.14 `exchangedata()` fails with `Operation not supported`. This is due to the fact that Apple did deprecate the `exchangedata()` function in 10.13 and replaced it with `renamex_np()`. `exchangedata()` does not work on APFS volumes backing the loopback volume. So if you use `renamex_np()` in LoopbackFS everything works just fine on 10.13.

```
- (BOOL)exchangeDataOfItemAtPath:(NSString *)path1
                  withItemAtPath:(NSString *)path2
                           error:(NSError **)error {
  NSString* p1 = [rootPath_ stringByAppendingString:path1];
  NSString* p2 = [rootPath_ stringByAppendingString:path2];
  
  int ret = renamex_np([p1 UTF8String], [p2 UTF8String], RENAME_SWAP);
  if ( ret < 0 ) {
    if ( error ) {
      *error = [NSError errorWithPOSIXCode:errno];
    }
    return NO;
  }
  return YES;
}
```

**Comment by bfleischer** [comment] 2019-05-01 17:27
@kaushiks Thanks. I've already merged your fix in the upcoming 3.9.0 release. This is the version I ran the tests with.

**Comment by kaushiks** [comment] 2019-05-01 17:39
@bfleischer Thank you!

**Comment by bfleischer** [comment] 2019-05-01 19:51
For me @sarat-ravi's test code works fine on 10.12, 10.13, and 10.14, so I'm closing the issue.

**Closed by bfleischer** 2019-05-01 19:51 UTC
Labels: bug
