### ISSUE TITLE
Can't show custom icon correctly 

### ISSUE THREAD

**Issue by samuelpfchoi** [osxfuse/osxfuse#86] opened 2013-06-04 08:20 UTC
The following is my experiment,

I have two files. Both file name are same name, e.g. t1.jpg and both file are set a custom icon with different image. 

Execute LoopbackFS and open the mounted volume using Finder, and then copied the first t1.jpg into mounted volume. It showed the custom icon of the first file correctly. However, when I copied the second t1.jpg to replaced the first one, the Finder still showed the first file custom icon.

Although I deleted the file and then copied the second t1.jpg into mounted volume, Finder still showed the custom icon of the first file

**Comment by bfleischer** [comment] 2016-02-13 21:46
I cannot reproduce the issue with the latest version of osxfuse, therefore I'm closing the ticket. Feel free to re-open it if this is still an issue.

**Closed by bfleischer** 2016-02-13 21:46 UTC
