### ISSUE TITLE
Fehler in den (macFUSE) Systemeinstellungen nach Installation

### ISSUE THREAD

**Issue by bonifatius5** [osxfuse/osxfuse#792] opened 2021-03-22 19:23 UTC
Ich habe die neuste Staple Version von macFUSE (4.1.0) installiert. Ich nutze ein MacBook Pro M1. Ich habe die Kernel Erweiterungen in den Startoptionen angepasst. Beim Versuch, die macFUSE-Einstellungen in den Systemeinstellungen zu starten kommt folgende Fehlermeldung (siehe Bildschirmfoto). Eine Idee, woran es liegen kann?
<img width="875" alt="Bildschirmfoto 2021-03-22 um 20 23 28" src="https://user-images.githubusercontent.com/81188743/112046558-7e705b00-8b4c-11eb-9377-aea63465b79c.png">

**Comment by bonifatius5** [comment] 2021-03-27 06:56
The problem still exists. Here again in English: I have installed the latest Staple version of macFUSE (4.1.0). I am using a MacBook Pro M1. I have adjusted the kernel extensions in the startup options. When trying to launch macFUSE preferences in System Preferences the following error message comes up (see screenshot). Any idea what the problem could be?

https://user-images.githubusercontent.com/81188743/112712795-d6eb8380-8ed1-11eb-88f2-ca85a1bf10b0.mov

**Comment by gregBerthelot** [comment] 2021-04-15 12:21
Same issue here https://github.com/osxfuse/osxfuse/issues/799

**Comment by bfleischer** [comment] 2021-04-15 12:28
Did you install Rosetta 2?

**Comment by gregBerthelot** [comment] 2021-04-15 12:44
No. I was waiting your native version to install macFuse so for my use case I don't want to install Rosetta since we can't remove it.

**Comment by themiguelamador** [comment] 2021-04-15 12:53
Got the error not on M1.

**Comment by bfleischer** [comment] 2021-04-15 12:57
Do you still get this error after rebooting?

**Comment by gregBerthelot** [comment] 2021-04-15 13:07
For myself yes

**Comment by bfleischer** [comment] 2021-04-15 13:11
Can you open Console.app and check the log messages when you click on the macFUSE preference pane? This might tell us what's causing the issue.

In the sidebar of Console.app there should be a crash log section. Could you check if it contains any macFUSE related crashes? If this is the case, it would be great if you could attach the crash log to this ticket.

**Comment by gregBerthelot** [comment] 2021-04-15 13:14
[macfuse-prefs-crash-report.txt](https://github.com/osxfuse/osxfuse/files/6318247/macfuse-prefs-crash-report.txt)

**Comment by bonifatius5** [comment] 2021-04-15 13:22
I will also create a crash report later today and make it available. I have a virgin Apple M1 without Rosetta2 in use.

**Comment by bonifatius5** [comment] 2021-04-15 15:01
[legacyLoader-arm64_2021-04-15-155255_MacBook-Pro-von-Sebastian.txt](https://github.com/osxfuse/osxfuse/files/6318965/legacyLoader-arm64_2021-04-15-155255_MacBook-Pro-von-Sebastian.txt)

here is my crash report

**Comment by gregBerthelot** [comment] 2021-04-28 15:47
@bfleischer will the issue been fixed in next release?

**Comment by bonifatius5** [comment] 2021-04-28 15:52
That would be great if it could be fixed with the next release

**Comment by bfleischer** [comment] 2021-05-16 01:00
The crash should be addressed in the new 4.1.1 release. Please re-open the ticket in case you can still reproduce the issue with the new release.

**Closed as completed by bfleischer** 2021-05-16 01:00 UTC

**Comment by bonifatius5** [comment] 2021-05-16 06:50
Ich hatte gehofft, dass die neue Version das Problem löst. Leider ist es auch mit der neuen Version 4.1.1 so, wie beschrieben. Bitte den Fall wieder öffnen.

I had hoped that the new version would solve the problem. Unfortunately, even with the new version 4.1.1 it is as described. Please open the case again.

**Comment by bfleischer** [comment] 2021-05-16 10:09
@bonifatius5 Please send me a new crash log for version 4.1.1.

**Comment by bonifatius5** [comment] 2021-05-16 18:34
Hier ist der gewünschte Absturz Bericht. Hier noch ergänzend Details zu meiner Hard- und Software:
Here is the desired crash report. Here are some additional details about my hardware and software:

macOS BigSur (11.3.1)
MacBook Pro (13", M1, 2020)
Rosetta 2 wurde nicht installiert (soll auch so bleiben / should stay that way)
[legacyLoader-arm64_2021-05-16-202726_MacBook-Pro-von-Sebastian.txt](https://github.com/osxfuse/osxfuse/files/6489767/legacyLoader-arm64_2021-05-16-202726_MacBook-Pro-von-Sebastian.txt)

**Comment by bfleischer** [comment] 2021-05-16 21:42
Please try again with version 4.1.2

**Comment by bonifatius5** [comment] 2021-05-17 12:46
Es kam die Meldung 'Systemerweiterungscache neu anlegen' vor dem Neustart. Dann 2 x Neustart. Jetzt klappt es :-)
<img width="875" alt="Bildschirmfoto 2021-05-17 um 14 44 44" src="https://user-images.githubusercontent.com/81188743/118490819-a29c8280-b71e-11eb-9509-eaf458c584c0.png">
