### ISSUE TITLE
Unable to map virtual drives in macOS Big Sur 11.1, Apple silicon macbook

### ISSUE THREAD

**Issue by Char1esFu** [osxfuse/osxfuse#763] opened 2020-12-22 06:07 UTC
![image](https://user-images.githubusercontent.com/58471920/102854325-467a4e80-445d-11eb-8e4e-923984eed772.png)

Thanks to macFUSE 4.0.4 update, cloud drive mapping has been available on new apple silicon macbooks. But in the latest version it's not working again. the main drive I use is called pCloud, it can map cloud drive as if it works locally while occupying no more than 5GB of cache file. The screenshot is from the conversation between me and their support team.

Apple supposedly blocked system extension again, making it impossible for developers to make virtual drive work. From what I experienced, every time I open the software, there'll be a popout saying that system extension blocked, a program tried to load new system extension(s) signed by "PCLOUD LTD" that need to be updated by the developer. 
![image](https://user-images.githubusercontent.com/58471920/102855037-c81eac00-445e-11eb-9ab3-c0fd0ae2e398.png)

In the mean time no matter how many times I restart the system, system extension is blocked anyway. Since macFUSE is the critical component for this feature to work on macOS, I wonder if it's a technical issue from macFUSE, because I've experienced similar issues from other virutal drive mapping software (cloudmounter to be specific)

**Comment by johnothwolo** [comment] 2021-01-07 05:28
Apple looks like they're now completely locking down macOS, which feels like a middle finger to free software (like Linus to Nvidia). @bfleischer do you think FUSE will survive this?

**Comment by Char1esFu** [comment] 2021-01-07 07:45
> Apple looks like they're now completely locking down macOS, which feels like a middle finger to free software (like Linus to Nvidia). @bfleischer do you think FUSE will survive this?

Hi, it seems like the problem is not with macFUSE, but with software developer. Yesterday pcloud support staff contacted me by email that they have already updated the software for macOS 11.1, making it functional again to mount virtual drive to Finder. It's working for both macFUSE 4.0.4 and 4.0.5.

**Comment by bfleischer** [comment] 2021-01-07 09:42
Let me start by saying that pCloud is not to blame here. In macOS 11 Apple completely rewrote the Kext Manager component. Unfortunately, with all new software there are bugs. Since the first release of macOS 11, I raised 11 issues with Apple. Four of the issues have been addressed in the meantime. Seven are currently open. For three of these seven remaining issues, FUSE contains workarounds. This leaves 4 issues that can prevent third-party kernel extension from being loaded. This is true for macFUSE and pCloud.

@johnothwolo FUSE will survive this. As soon as Apple has addressed the remaining issues, FUSE will work like before. There is definitely a need for full-featured third party file systems. So far Apple has not announced a new non-kernel API for developing file systems on macOS. If they do, I will update FUSE to use the new API.

**Comment by BernhardMB** [comment] 2021-01-16 14:34
@bfleischer Are there maybe some news meanwhile ? I am having the same problem, when trying to start Veracrypt using Fuse on an M1 MacBook. When I am trying "advanced" settings, it suggests me some modifications in security settings for kernel extensions (see attached screenshot). I didn't try this because I would not feel very comfortable doing this, also I am not sure if it would change something.
Thanks
Bernhard



<img width="286" alt="Bildschirmfoto 2021-01-16 um 10 50 25" src="https://user-images.githubusercontent.com/77538832/104814500-8f7cb300-580f-11eb-881f-93dcb94f6596.png">

**Comment by bfleischer** [comment] 2021-01-16 14:44
@BernhardMB On M1 Macs you need to allow loading third party kernel extensions in recovery mode before you will be able to use macFUSE. This is the way Apple has designed the process on M1 Macs. There is currently no way around this. Please follow the instructions on the screenshot you posted.

**Comment by williamhoney** [comment] 2021-04-16 06:28
@bfleischer is there still 'no way around it' — i.e. we need to "allow loading  third party kernel extensions in recovery mode before you will be able to use macFUSE"?

And if so, can we go and disable third party kernel extensions after installing macfuse then?

**Comment by bfleischer** [comment] 2021-04-16 12:41
@williamhoney Currently there is only one API for developing full-featured file systems and this is the VFS kernel API that macFUSE uses. There is no alternative API. Apple needs to create such an alternative API first, before I can update macFUSE to use this new API instead of the old kernel API. Until Apple introduces such a new API, there is no way around enabling loading third-party kernel extensions in recovery mode.

> And if so, can we go and disable third party kernel extensions after installing macfuse then?

If you disable loading third-party kernel extensions macFUSE will stop working.

Please keep in mind that enabling third-party kernel extensions in recovery mode does not really lower the security of your system. You will still be propped by macOS and have to click the allow button for every third-party kernel extension that you want to load. This is exactly the same process you had to go through on macOS 10.14 or macOS 10.15.

**Comment by E-Baler** [comment] 2021-04-27 22:04
Same problem on intel mojave..

**Comment by panolens** [comment] 2021-04-28 15:26
Updating to bigSur 11.3 solved the problem for me - M1 - MacBook Air

with macFUSE 4.1.
Now I can write to cryptomator again without crashing my MacBook Air

**Comment by yin-ori** [comment] 2021-07-06 03:29
I have actually setup everything according to manual, updated on the new fuse 4.2 and yet my MacBook m1 breaks completely and by completely I mean finder is crashing on start (pCloud used to be a startprogram and I cannot change that now as finder crashes and won’t reopen on restart). Please help 😭

It worked until one month ago, then started to not be able to open pCloud from time to time and when I updated pCloud and fuse it completely crashed 😭

**Comment by koolerking730** [comment] 2021-07-27 08:37
Any more news on Apple releaseing API for Fuse? We use Lucid Link for all our production workflow!

**Closed as completed** 2021-09-11 02:39 UTC
