### ISSUE TITLE
umount hangs when network changed

### ISSUE THREAD

**Issue by avegetablechicken** [osxfuse/osxfuse#943] opened 2023-03-28 08:43 UTC
I install sshfs and macfuse by homebrew. It works well but when the network changed, it taks a long time to umount.

macOS version: 12.6

ps: text rendering of Chrome tab titles come into some mistakes when I install sshfs and enable the kernel extension. Not sure if they were related.

**Comment by jainraje** [comment] 2023-03-31 18:42
I just updated to Big Sur 11.7.5 and macFUSE v4.4.2 and both umount and diskutil unmount now fail. Only solution I've found is to reboot. Prior to the update diskutil unmount always seemed to work fine. This is a new phenomenon with the latest update/combo. Please advise. Thank-you! 

Update:
The followings unmount:
diskutil unmount force ~/mounts/mypath/

**Comment by bfleischer** [comment] 2024-04-15 07:26
> I install sshfs and macfuse by homebrew. It works well but when the network changed, it taks a long time to umount.

How long is "a long time" approximately? By default, there is a 60 seconds timeout for file system operations. After 60 seconds  have passed without the file system daemon (sshfs, in your case) responding, the macFUSE kernel extension sends an interrupt request to the file system daemon. In case the file system does not respond within 60 seconds, the file system is marked as dead. This means, by default, it should not take significantly longer than 2 minutes to unmount an unresponsive volume.

> ps: text rendering of Chrome tab titles come into some mistakes when I install sshfs and enable the kernel extension. Not sure if they were related.

I don't see how macFUSE could interfere with text rending and don't think this is caused by macFUSE.

**Comment by bfleischer** [comment] 2024-04-15 07:26
@jainraje Is this still an issue with the latest version of macFUSE?

**Comment by jainraje** [comment] 2024-08-23 14:02
I’m just seeing this message. The issue is no longer present w latest release. Can be closed. Thank you.

**Closed as completed** 2024-11-26 21:48 UTC
