### ISSUE TITLE
Latest notarized kexts are not stapled with tickets

### ISSUE THREAD

**Issue by DigitalGuardianDev** [osxfuse/osxfuse#617] opened 2019-08-26 11:29 UTC
Hi,

If the network is down when the osxfuse is run for the first time, the fuse is not starting has the kext is not stapled with the ticket.

Can you please staple the ticket before creating the package file.

**Comment by bfleischer** [comment] 2019-08-31 18:02
I upload the final release Disk Image to Apple's notarization service. As such it is not possible to staple the ticket to the kernel extensions. The ticket is stapled to the Disk Image.

**Comment by bfleischer** [comment] 2019-08-31 18:11
I can reproduce the issue on macOS 10.14. I assumed the ticket stapled to the disk image would be sufficient but apparently this is not the case. Stapling the ticket to the individual kernel extensions would complicate the build process significantly.

**Comment by bfleischer** [comment] 2019-12-08 21:39
The issue is addressed in FUSE for macOS 3.10.4.

**Closed as completed by bfleischer** 2019-12-08 21:39 UTC
Labels: enhancement
