### ISSUE TITLE
Kernel panic for osxfuse 3.8.0 on macOS 10.13

### ISSUE THREAD

**Issue by kevin-zhu-ca** [osxfuse/osxfuse#510] opened 2018-06-11 01:59 UTC
Hi guys:
    I'm getting kernel panic for osxfuse 3.8.0 on macOS 10.13.5. I've checked system log, and it seems osxfuse kext has a conflict with an App I've already installed. As far as I know is that my App calls system function `vnode_getattr`, which is hooked by osxfuse and then the kernel panic occurrs. Could you please help check this out? 
Thanks.

Below is the crash report:

Fri Jun  8 15:46:25 2018

*** Panic Report ***
panic(cpu 2 caller 0xffffff801d387d3d): Kernel trap at 0xffffff801d4c9c74, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x0000000000000008, CR3: 0x0000000215df0109, CR4: 0x00000000003627e0
RAX: 0x0000000000000000, RBX: 0xffffff8057f381f0, RCX: 0x0000000003000000, RDX: 0xffffff804c6482a0
RSP: 0xffffff91529fb2c0, RBP: 0xffffff91529fb2c0, RSI: 0x0000000000000002, RDI: 0x0000000000000000
R8:  0xffffff8047505480, R9:  0x0000000000000000, R10: 0x0000000000000007, R11: 0x0000000000000000
R12: 0x0000000000000000, R13: 0x0000000000000020, R14: 0xffffff91529fb450, R15: 0xffffff8052bc3700
RFL: 0x0000000000010246, RIP: 0xffffff801d4c9c74, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x0000000000000008, Error code: 0x0000000000000000, Fault CPU: 0x2, PL: 0, VF: 0

Backtrace (CPU 2), Frame : Return Address
0xffffff91529fad70 : 0xffffff801d26d166 
0xffffff91529fadc0 : 0xffffff801d395824 
0xffffff91529fae00 : 0xffffff801d387b10 
0xffffff91529fae80 : 0xffffff801d21f180 
0xffffff91529faea0 : 0xffffff801d26cbdc 
0xffffff91529fafd0 : 0xffffff801d26c99c 
0xffffff91529fb030 : 0xffffff801d387d3d 
0xffffff91529fb1b0 : 0xffffff801d21f180 
0xffffff91529fb1d0 : 0xffffff801d4c9c74 
0xffffff91529fb2c0 : 0xffffff7fa07be73f 
0xffffff91529fb390 : 0xffffff7fa07bc6ff 
0xffffff91529fb3c0 : 0xffffff801d4ca7f3 
0xffffff91529fb430 : 0xffffff7fa0782a25 
0xffffff91529fb600 : 0xffffff7fa078aea6 
0xffffff91529fb6d0 : 0xffffff7fa078c815 
0xffffff91529fb730 : 0xffffff7fa0780cc8 
0xffffff91529fb7e0 : 0xffffff7fa07903b5 
0xffffff91529fb890 : 0xffffff801d6e8bc3 
0xffffff91529fb8f0 : 0xffffff801d4c0b2f 
0xffffff91529fb980 : 0xffffff801d4aba0f 
0xffffff91529fbbc0 : 0xffffff801d4ac454 
0xffffff91529fbf40 : 0xffffff801d803bd8 
0xffffff91529fbfa0 : 0xffffff801d21f966 
      Kernel Extensions in backtrace:
         com.trendmicro.kext.filehook(2.5)[1B5E5DB1-15BE-3CE8-836A-C6F1FD0427B0]@0xffffff7fa077e000->0xffffff7fa0794fff
         com.github.osxfuse.filesystems.osxfuse(3.8)[638C0165-0C41-3742-A972-2F8E605F1AA4]@0xffffff7fa07b5000->0xffffff7fa07cefff

BSD process name corresponding to current thread: Finder

Mac OS version:
17F77

Kernel version:
Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64
Kernel UUID: CC1699EE-71B5-3AF1-AAA3-6DBD16222B92
Kernel slide:     0x000000001d000000
Kernel text base: 0xffffff801d200000
__HIB  text base: 0xffffff801d100000
System model name: MacBookPro14,2 (Mac-CAD6701F7CEA0921)

System uptime in nanoseconds: 5469515254174
last loaded kext at 5469111185395: com.github.osxfuse.filesystems.osxfuse	3.8.0 (addr 0xffffff7fa07b5000, size 106496)
last unloaded kext at 4910075450883: com.apple.driver.AppleXsanScheme	3 (addr 0xffffff7fa076a000, size 32768)
loaded kexts:
com.github.osxfuse.filesystems.osxfuse	3.8.0
com.trendmicro.kext.filehook	2.5.0
com.trendmicro.kext.KERedirect	2.5.0
zoom.us.ZoomAudioDevice	1.2
com.logitech.manager.kernel.driver	6.90.1
com.apple.driver.usb.AppleUSBHostBillboardDevice	1.0
com.apple.filesystems.smbfs	3.2.3
com.apple.driver.AGPM	110.23.37
com.apple.driver.ApplePlatformEnabler	2.7.0d0
com.apple.driver.X86PlatformShim	1.0.0
com.apple.filesystems.autofs	3.0
com.apple.driver.AudioAUUC	1.70
com.apple.driver.AppleUpstreamUserClient	3.6.5
com.apple.driver.AppleGraphicsDevicePolicy	3.18.52
com.apple.AGDCPluginDisplayMetrics	3.18.52
com.apple.driver.AppleHDA	281.52
com.apple.driver.AppleHV	1
com.apple.driver.AppleHIDALSService	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOBluetoothSerialManager	6.0.6f2
com.apple.driver.eficheck	1
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.pmtelemetry	1
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleIntelPCHPMC	2.0.1
com.apple.driver.AppleThunderboltIP	3.1.1
com.apple.driver.AppleEmbeddedOSSupportHost	1
com.apple.driver.AppleBacklight	170.12.6
com.apple.driver.AppleMCCSControl	1.5.5
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleIntelKBLGraphics	10.3.4
com.apple.driver.AppleIntelKBLGraphicsFramebuffer	10.3.4
com.apple.filesystems.apfs	748.51.0
com.apple.filesystems.hfs.kext	407.50.6
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.AppleSystemPolicy	1.0
com.apple.driver.AppleTopCaseHIDEventDriver	133
com.apple.driver.AirPort.BrcmNIC	1241.31.1a9
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	6.1
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	183
com.apple.security.TMSafetyNet	8
com.apple.security.quarantine	3
com.apple.driver.usb.cdc.acm	5.0.0
com.apple.driver.usb.cdc.ecm	5.0.0
com.apple.driver.AppleUSBMergeNub	900.4.1
com.apple.driver.AppleXsanScheme	3
com.apple.kext.triggers	1.0
com.apple.driver.AppleGraphicsControl	3.18.52
com.apple.driver.DspFuncLib	281.52
com.apple.kext.OSvKernDSPLib	526
com.apple.iokit.IOAVBFamily	680.2
com.apple.plugin.IOgPTPPlugin	680.15
com.apple.iokit.IOEthernetAVBController	1.1.0
com.apple.iokit.IOBluetoothHostControllerUARTTransport	6.0.6f2
com.apple.iokit.IOBluetoothHostControllerTransport	6.0.6f2
com.apple.driver.AppleSSE	1.0
com.apple.driver.AppleIntelLpssUARTv1	3.0.60
com.apple.driver.AppleIntelLpssUARTCommon	3.0.60
com.apple.driver.AppleOnboardSerial	1.0
com.apple.iokit.IOSkywalkFamily	1
com.apple.iokit.IOSerialFamily	11
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.AppleGPUWrangler	3.18.52
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.iokit.IONDRVSupport	519.19
com.apple.AppleGraphicsDeviceControl	3.18.52
com.apple.iokit.IOAcceleratorFamily2	378.18.1
com.apple.iokit.IOSurface	211.12
com.apple.driver.AppleHDAController	281.52
com.apple.iokit.IOGraphicsFamily	519.19
com.apple.iokit.IOHDAFamily	281.52
com.apple.iokit.IOAudioFamily	206.5
com.apple.vecLib.kext	1.2.0
com.apple.driver.usb.cdc.ncm	5.0.0
com.apple.driver.usb.AppleUSBiBridge	1.0
com.apple.driver.usb.IOUSBHostHIDDevice	1.2
com.apple.driver.usb.cdc	5.0.0
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.driver.usb.AppleUSBHub	1.2
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.AppleActuatorDriver	1404.4
com.apple.driver.AppleHIDKeyboard	205
com.apple.driver.AppleHSBluetoothDriver	133
com.apple.driver.AppleMultitouchDriver	1404.4
com.apple.driver.AppleInputDeviceSupport	1404.3
com.apple.driver.AppleHSSPIHIDDriver	53
com.apple.driver.AppleThunderboltDPInAdapter	5.5.4
com.apple.driver.AppleThunderboltDPAdapterFamily	5.5.4
com.apple.driver.AppleThunderboltPCIDownAdapter	2.1.3
com.apple.driver.AppleHPM	3.1.3
com.apple.driver.AppleIntelLpssI2CController	3.0.60
com.apple.driver.AppleHSSPISupport	53
com.apple.driver.AppleThunderboltNHI	4.7.2
com.apple.iokit.IOThunderboltFamily	6.7.8
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.driver.corecapture	1.0.4
com.apple.iokit.IONVMeFamily	2.1.0
com.apple.driver.AppleIntelLpssSpiController	3.0.60
com.apple.driver.AppleIntelLpssDmac	3.0.60
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.driver.AppleIntelLpssI2C	3.0.60
com.apple.driver.AppleIntelLpssGspi	3.0.60
com.apple.driver.usb.AppleUSBXHCIPCI	1.2
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.DiskImages	480.60.1
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	439.60.2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.iokit.IOUSBMassStorageDriver	140.50.3
com.apple.iokit.IOSCSIBlockCommandsDevice	404.30.2
com.apple.iokit.IOSCSIArchitectureModelFamily	404.30.2
com.apple.iokit.IOStorageFamily	2.1
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.iokit.IOTimeSyncFamily	680.15
com.apple.iokit.IONetworkingFamily	3.4
com.apple.driver.IOBluetoothHIDDriver	6.0.6f2
com.apple.iokit.IOBluetoothFamily	6.0.6f2
com.apple.iokit.IOReportFamily	31
com.apple.iokit.IOUSBHIDDriver	900.4.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.corecrypto	1.0

EOF

System Profile:
Network Service: Wi-Fi, AirPort, en0
Boot Volume File System Type: apfs
Memory Module: BANK 0/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C3531324D3332443250462D3039
Memory Module: BANK 1/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C3531324D3332443250462D3039
USB Device: USB 3.0 Bus
USB Device: USB2.0 Hub
USB Device: USB-HID Keyboard
USB Device: Generic Billboard Device
USB Device: iBridge
USB Device: USB3.0 Hub
Thunderbolt Bus: MacBook Pro, Apple Inc., 33.1
Thunderbolt Bus: MacBook Pro, Apple Inc., 33.1
Model: MacBookPro14,2, BootROM MBP142.0175.B00, 2 processors, Intel Core i5, 3.1 GHz, 8 GB, SMC 2.44f1
Graphics: Intel Iris Plus Graphics 650, Intel Iris Plus Graphics 650, Built-In
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x171), Broadcom BCM43xx 1.0 (7.77.37.31.1a9)
Bluetooth: Version 6.0.6f2, 3 services, 27 devices, 1 incoming serial ports

**Comment by bfleischer** [comment] 2018-06-11 06:18
This is the symbolicated backtrace:

```
Backtrace (CPU 2), Frame : Return Address
0xffffff91529fad70 : 0xffffff801d26d166 handle_debugger_trap (in kernel) (debug.c:1020)
0xffffff91529fadc0 : 0xffffff801d395824 kdp_i386_trap (in kernel) (kdp_machdep.c:458)
0xffffff91529fae00 : 0xffffff801d387b10 kernel_trap (in kernel) (trap.c:769)
0xffffff91529fae80 : 0xffffff801d21f180 trap_from_kernel (in kernel) + 38
0xffffff91529faea0 : 0xffffff801d26cbdc panic_trap_to_debugger (in kernel) (debug.c:724)
0xffffff91529fafd0 : 0xffffff801d26c99c panic (in kernel) (debug.c:0)
0xffffff91529fb030 : 0xffffff801d387d3d kernel_trap (in kernel) (trap.c:826)
0xffffff91529fb1b0 : 0xffffff801d21f180 trap_from_kernel (in kernel) + 38
0xffffff91529fb1d0 : 0xffffff801d4c9c74 vfs_context_ucred (in kernel) (kpi_vfs.c:1369)
0xffffff91529fb2c0 : 0xffffff7fa07be73f fuse_vnop_getattr (in osxfuse) (fuse_vnops.c:794)
0xffffff91529fb390 : 0xffffff7fa07bc6ff fuse_biglock_vnop_getattr (in osxfuse) (fuse_biglock_vnops.c:161)
0xffffff91529fb3c0 : 0xffffff801d4ca7f3 vnode_getattr (in kernel) (kpi_vfs.c:3338)
0xffffff91529fb430 : 0xffffff7fa0782a25 ??? (com.trendmicro.kext.filehook)
0xffffff91529fb600 : 0xffffff7fa078aea6 ??? (com.trendmicro.kext.filehook)
0xffffff91529fb6d0 : 0xffffff7fa078c815 ??? (com.trendmicro.kext.filehook)
0xffffff91529fb730 : 0xffffff7fa0780cc8 ??? (com.trendmicro.kext.filehook)
0xffffff91529fb7e0 : 0xffffff7fa07903b5 ??? (com.trendmicro.kext.filehook)
0xffffff91529fb890 : 0xffffff801d6e8bc3 kauth_authorize_fileop (in kernel) (kern_authorization.c:567)
0xffffff91529fb8f0 : 0xffffff801d4c0b2f vn_open_auth (in kernel) (vfs_vnops.c:645)
0xffffff91529fb980 : 0xffffff801d4aba0f open1 (in kernel) (vfs_syscalls.c:3500)
0xffffff91529fbbc0 : 0xffffff801d4ac454 open (in kernel) (vfs_syscalls.c:3897)
0xffffff91529fbf40 : 0xffffff801d803bd8 unix_syscall64 (in kernel) (systemcalls.c:382)
0xffffff91529fbfa0 : 0xffffff801d21f966 hndl_unix_scall64 (in kernel) + 22
Kernel Extensions in backtrace:
com.trendmicro.kext.filehook(2.5)[1B5E5DB1-15BE-3CE8-836A-C6F1FD0427B0]@0xffffff7fa077e000->0xffffff7fa0794fff
com.github.osxfuse.filesystems.osxfuse(3.8)[638C0165-0C41-3742-A972-2F8E605F1AA4]@0xffffff7fa07b5000->0xffffff7fa07cefff
```

To me it looks like Trend Micro is sending a NULL `vfs_context_t` to FUSE when calling vnode_getattr. This is definitely nothing they should be doing. I think I can work around this, but the culprit here is Trend Micro.

**Comment by kevin-zhu-ca** [comment] 2018-06-11 06:25
Hi Benjamin:
Thank you for your help! I'll check that out with Trend Micro :-)

**Comment by bfleischer** [comment] 2018-06-18 01:37
Version 3.8.1 contains a workaround for this issue. It would be great if you could confirm that the issue is indeed resolved.

**Comment by kevin-zhu-ca** [comment] 2018-06-19 09:29
Hi @bfleischer:
      Thank you for your workaround. I've verified Fuse 3.8.1 and the issue is fixed. Yet after I performed command `ifuse iPhone`, the mounting folder iPhone disappears and iPhone is not mounted, which feels a little weird.
      Also, Trend Micro as well provides a fix of this issue. So I wonder if possible, it is better that it could work correctly along with the latest bug-free version of Trend Micro app. :-)
Thanks.

**Comment by Sebastian-blu** [comment] 2018-07-26 00:05
I just got my 2018 mbp migrated from my 2016 mbp. I enabled fuse and restarted and now the computer won't get pas the loading screen and I can't get it to start in safe mode. The only think I enabled in security was fuse. Im not sure what kernel panic is but I think maybe that is what is happening here? any advice would be amazing im lost here it was working and now its dead

**Comment by bfleischer** [comment] 2018-09-26 19:45
The kernel panic seem to be resolved, so I'm closing the issue.

**Closed as completed by bfleischer** 2018-09-26 19:45 UTC
Labels: bug
