### ISSUE TITLE
[Tracking] Support macOS Mojave

### ISSUE THREAD

**Issue by 19h** [osxfuse/osxfuse#508] opened 2018-06-05 23:11 UTC
This is a tracking issue for MacOS Mojave support. At the time of writing the distributed binary doesn't run on said OS version and it should be figured out if there is anything broken by Mojave in the lower-level code,

🐝

**Comment by jcameronjeff** [comment] 2018-06-09 18:43
Same issue here.

**Comment by XNinety9** [comment] 2018-06-12 11:52
same for me!

**Comment by katzly** [comment] 2018-06-13 02:34
same same

**Comment by ctp2nd** [comment] 2018-06-13 15:43
[Edits added because @bfleischer said this is not a good idea]

I think I may have found a functional [But Very Bad] solution to running OSXFuse on Mojave:

In terminal [You probably shouldn’t]:

sudo cp -R /Library/Filesystems/osxfuse.fs/Contents/Extensions/10.13 /Library/Filesystems/osxfuse.fs/Contents/Extensions/10.14

Backstory [I’m not a smart man]:  I have a script that uses sshfs & osxfuse to mount a few remote directories.  After upgrading to Mojave and attempting to run said script, I got an error saying that it (osxfuse) wouldn't work on my OS.  I tried compiling to no avail.  I then started digging around in the osxfuse.fs package that was installed before the Mojave upgrade, and noticed that in the Extensions folder, 10.13 was a simlink to the 10.11 folder.  So, I copied it and made it 10.14... re-ran the script, and everything mounted.

If someone else could [You shouldn’t] try and see if it works for them, we may have a temporary [and Very Dangerous] solution to the Mojave problem.

![screen shot 2018-06-11 at 12 59 17 pm](https://user-images.githubusercontent.com/957220/41362271-8ef536be-6ef6-11e8-897a-0970da5f8b5b.png)

**Comment by bfleischer** [comment] 2018-06-13 17:22
@ctp2nd I cannot stress enough that this is a really bad idea. The FUSE kernel extension needs to be patched for almost every new release of macOS. This is the case for Mojave. FUSE relies on kernel data structures that change from macOS release to macOS release. Creating the symlink like you did results in FUSE operating with the wrong offsets. In this particular case your system might deadlock and you might loose data.

**Comment by alexk403** [comment] 2018-06-13 17:26
@ctp2nd pending the severity of what @bfleischer just said... I can confirm this workaround does indeed work and can now mount, read, and write files successfully on 10.14.

**Comment by ctp2nd** [comment] 2018-06-13 17:51
@bfleischer, thanks for the warning.  The only reason I thought to copy/paste & rename the symlink is due to the ones that are already there indicating that OSXs 10.13 & 10.12 point at and use the FUSE kernel extension for OSX 10.11, 10.10 uses 10.9, and 10.8 & 10.7 use 10.6’s.  I see that the kext’s do change periodically and I don’t doubt that Mojave will/may need a new one.  

@alexk403 Thanks for the confirmation.  Sorry if I kill your machine and/or data.

**Comment by bfleischer** [comment] 2018-06-13 17:57
@ctp2nd The different extensions for 10.5, 10.6, 10.9, and 10.11 are due to new API that Apple has added in these releases. Unlike normal apps, kernel extension can not be built with backwards compatibility. There is no deployment target setting. This means every time Apple adds a new kernel API that FUSE uses, I add a new kernel extension. But that's only half of the story. At runtime each kernel extension checks which version of macOS is running and uses other offsets to extract the required data from kernel data structures.

**Comment by ctp2nd** [comment] 2018-06-13 18:00
@bfleischer, thanks again.  This discussion reminds me why I normally just lurk and leave the commenting and suggestions to you experts.  I really do appreciate the information.

**Comment by XNinety9** [comment] 2018-06-16 10:37
Any news from osxfuse maintainer? I heavily rely on osxfuse for my day-to-day work, and as a dev I need to stick to osx Mojave 😭

**Comment by bfleischer** [comment] 2018-06-18 06:16
A few hours ago I have released version 3.8.1, which adds, among other things, experimental support for macOS 10.14. It would be great if you could give it a test drive and let me know if you ran into any issues.

**Comment by XNinety9** [comment] 2018-06-18 08:52
Thanks a lot, I'm installing it right now.

**Comment by Spydar007** [comment] 2018-06-18 11:52
Working fine here, thanks a lot!

**Comment by Qiaoyf96** [comment] 2018-06-18 14:27
I tried to use sshfs to map a local folder to remote, and then my local folder just disappeared... when I want to recreate the folder, it is said "File exists."; when I want to cd the folder, it is said "the directory does not exist." 😂

**Comment by ctp2nd** [comment] 2018-06-18 15:05
@bfleischer just installed and it connected to all my remote mounts.  Thank you, I appreciate the work you do.

**Comment by alexk403** [comment] 2018-06-18 17:41
3.8.1 doesn't seem to be working with latest version of Transmit, can anyone else confirm or deny? When I click mount as disk, it loads for a couple seconds then stops, but nothing is mounted.

**Comment by crudehung** [comment] 2018-06-18 19:06
It also not working with the  latest version of pCloud and Veracrypt. 
10.14 Mojave cannot locate (or mount) the network drive or pCloud. In case of Veracrypt, something is missing after trying to mount the encrypted vault.

```
> /var/folders/13/zy_8gfxs6jv3ftkxxvc1_8640000gn/T//.veracrypt_aux_mnt1/control
> 
> VeraCrypt::FilesystemPath::GetType:48
```

_

**Comment by Spydar007** [comment] 2018-06-18 19:07
It's working for me with Veracrypt

**Comment by krlmrr** [comment] 2018-06-18 20:27
I can confirm. It’s not working with Transmit...

Thanks!

-Karl

**Comment by ghost** [comment] 2018-06-19 01:35
Another one here to confirm not working with Veracrypt per @crudehung 's error message. Same thing happens when attempting to create a new hidden volume or new file in general.

**Comment by katzly** [comment] 2018-06-19 05:03
not working with pcloud






On Mon, Jun 18, 2018 9:35 PM, MarsWanKenobi notifications@github.com  wrote:
Another one here to confirm not working with Veracrypt per @crudehung  's error
message.

**Comment by pavelnovac** [comment] 2018-06-19 10:18
Thx, it's working for me with Диск-О

**Comment by XNinety9** [comment] 2018-06-20 08:10
Not working with pCloud on macOS Mojave. pCloud client says nothing, but pCloud Drive can't mount.

**Comment by jerrycopus** [comment] 2018-06-25 13:18
Also confirming Crudehung's report of 3.8.1 issue with VeraCrypt 1.23-BETA0 on macOS 10.13.5 High Sierra. 3.8.0 works fine.

<img width="532" alt="screen shot 2018-06-24 at 7 37 39 pm" src="https://user-images.githubusercontent.com/17318530/41861024-c5b57d1c-7865-11e8-87ed-57c25d7334ca.png">

**Comment by Queequeg92** [comment] 2018-06-25 13:38
3.8.1 seems working with pCloud.

**Comment by austrasien** [comment] 2018-06-25 14:43
3.8.1 not working with pCloud on **macOS Mojave.**

**Comment by Queequeg92** [comment] 2018-06-26 00:44
@austrasien Try to install 3.8.1 with MacFuse Compatibility Layer. It works for me on macOS Mojave with pCloud.
![screen shot 2018-06-26 at 08 40 48](https://user-images.githubusercontent.com/8766653/41882718-0837e9ec-791d-11e8-830c-accec84597a2.png)

**Comment by austrasien** [comment] 2018-06-26 06:11
@Queequeg92 I've installed MacFuse Compatibility Layer but it still doesn't work.
Specs: MacBook Air (13" mid-2013) macOS Mojave bêta 10.14 (18A314h).

**Comment by wtfn2** [comment] 2018-06-26 21:30
<img width="420" alt="ohne titel" src="https://user-images.githubusercontent.com/40613401/41940238-5f7f3572-7998-11e8-8f66-41e9144cb977.png">

5K late '15 on Mojave public beta 1 with Fuse 3.8.1 and Veracrypt 1.2.3 Beta 0, vault on external USB drive.

Any news on 3.8.2? :-)

**Comment by bfleischer** [comment] 2018-06-26 21:35
Please raise the VeraCrypt issues with the VeraCrypt team. In Mojave you need root permissions to open devices. This might be causing the VeraCrypt issues. But this is something the VeraCrypt team needs to  look into.

**Comment by wtfn2** [comment] 2018-06-26 22:37
Boom! Working!

To other Veracrypt users: Just open Veracrypt with sudo via terminal and it will mount properly.

sudo /Applications/VeraCrypt.app/Contents/MacOS/VeraCrypt

Thanks bfleischer!

**Comment by marcmiquel** [comment] 2018-06-27 09:15
It does not work for me on Mojave.
I uninstalled it, installed it, installed with compatibility layer, and nothing.
I am using macOS Mojave Version 10.14 Beta (18A314k) with a MacBook Pro (2013).

I am not using Veracrypt nor Pcloud. I just need to mount a server location as a folder to work.

@bfleischer should I do something in particular?

**Comment by jerrycopus** [comment] 2018-06-27 23:56
> Please raise the VeraCrypt issues with the VeraCrypt team. In Mojave you need root permissions to open devices. This might be causing the VeraCrypt issues. But this is something the VeraCrypt team needs to look into.

Done: https://sourceforge.net/p/veracrypt/tickets/212/

**Comment by 19h** [comment] 2018-06-28 00:11
Requiring root permissions for device access in MacOS Mojave seems like a questionable design decision considering the upcoming radioactive fallout in the form of PrivilegedHelperTools.

I wonder if mounted ftp connections through Finder (using /System/Library/Filesystems/ftp.fs/Contents/Resources/mount_ftp) use undocumented APIs or some kind of permission sorcery to allow non-wheel users to access the mounts.

It occurred to me that Apple had previously implemented all of these synthetic network mounts as filesystems, so this probably isn't intrinsically a device? For all I know the filesystem mounters and agents (nfs, ftp) have root:wheel permissions.

**Comment by soleti** [comment] 2018-06-28 00:42
Same problem here. I am just trying to mount a folder on a remote server. If I run the usual `sshfs` command it doesn't return any error, but then when I try to access the folder it says `No such file or directory`. The weird thing is that if I try to remove the folder (that should not exist) I get `rm: app: Operation not permitted`. I tried also with `sudo`, same problem.

Update: apparently it's impossible to navigate the mounted folders (Finder and ls don't show them) *BUT* if I try to open a file with e.g. TextEdit (and sudo) it miraculously works! The filename completion doesn't work, so you need to know the path, but you can at least open the files.

My 2 cents that it's a weird permission issue.

Second update: opening a bash session with sudo allows you to navigate the mounted folder. Personally I don't like this approach, but if that's the only way, well, better than nothing ;)

**Comment by DavidHaynesHasGitHub** [comment] 2018-06-28 02:15
Having issues where the mounted drives arent appearing. Cant find them in finder, or with ls in the folders. Nothing special in how I am trying to access the server.

**Comment by MIchaelKa** [comment] 2018-06-28 15:42
3.8.1 does not work for me with LoopbackFS.
MacBook Pro (2017) and macOS Mojave Version 10.14 Beta (18A314k)
Has anybody tried to test it with LoopbackFS?

**Comment by gtimmy** [comment] 2018-06-29 08:52
@DavidHaynesHasGitHub Mounted drives are available via terminal with sudo rights, or Finder running with root, but it's unacceptable usage scenario, I suppose.

How osxfuse is going to be used in Finder?

**Comment by ktw5691** [comment] 2018-06-29 23:30
For anyone using encfs on Mac OS Mojave, I was able to install osxfuse from the 3.8 branch. I can start a <sudo bash> session and then use  <sudo encfs> and this will let me use the terminal to navigate the encrypted drive. However, I cannot access the drive thorough finder and echo concerns that using <sudo> to do all of this is not ideal.

**Comment by ktw5691** [comment] 2018-06-29 23:32
For anyone using encfs on Mac OS Mojave, I was able to install osxfuse from the 3.8 branch. I can start a session and then use `sudo bash` and `sudo encfs` and this will let me use the terminal to navigate the encrypted drive. However, I cannot access the drive thorough finder and echo concerns that using to do all of this is not ideal. Thanks to everyone above in this issue for the useful comments on getting osxfuse installed on Mojave :)

**Comment by idrassi** [comment] 2018-07-01 08:09
@bfleischer: As I’m the author of VeraCrypt, I have been redirected here concerning the issue happening with 3.8.1 Pre-release under OSX HighSierra 10.3.5. I understand that there are changes in OSX 10.4 but why OSXFuse requires now being root on OSX 10.3.5? Is not it possible to require root only on OSX 10.4?

Moreover, requiring root privileges to access OSXFuse mount points will dramatically change several use cases and it will even render it unusable is many situations. So if this is a new requirement of OSX 10.4, then a lot of people will stick to OSX 10.3.x for long time and OSXFuse should keep its existing behavior for OSX 10.3.x.

**Comment by jerrycopus** [comment] 2018-07-02 13:08
Confirming that version 3.8.2 (released 7/1/18) DOES work with macOS 10.13.5 and VeraCrypt 1.23-BETA0 now. Thanks!

**Comment by austrasien** [comment] 2018-07-02 13:35
Confirming that version 3.8.2 (released 7/1/18) DOES work with macOS 10.13.5 and pCloud 3.6.3 now. Thanks!

**Comment by marcmiquel** [comment] 2018-07-02 13:41
Thanks!
ᐧ

Missatge de austrasien <notifications@github.com> del dia dl., 2 de jul.
2018 a les 15:35:

**Comment by ktw5691** [comment] 2018-07-02 14:59
Confirming that the .dmg of osxfuse 3.8.2 works with encfs! Thanks!

**Comment by submarine89** [comment] 2018-07-02 15:01
osxfuse 3.8.2 works with Cryptomator on Mojave.

**Comment by gtimmy** [comment] 2018-07-02 15:13
Yes, it works for me as well on 10.14. I think it's happened because of these commits: [25af0](https://github.com/osxfuse/support/commit/25af01a8e16c1299253b91a742ce4b1d3b08139a) and 
[2cdc5](https://github.com/osxfuse/support/commit/2cdc56004c4552211b45ef6661b6f50903236ade). Now it works again! Thanks!

**Comment by alexk403** [comment] 2018-07-02 18:01
3.8.2 confirmed as working on latest Mojave Beta 2 with latest version of Transmit/Transmit Disk. Thanks a lot @bfleischer !!

**Comment by wtfn2** [comment] 2018-07-03 07:15
3.8.2 works with Veracrypt 1.23 Beta 0. No root needed.

**Comment by MuhsinFatih** [comment] 2018-07-09 19:54
I am on macOS Mojave 10.14 (18A314h), neither version (3.8.1, 3.8.2) works for me. I get the following on 3.8.1:
![image](https://user-images.githubusercontent.com/8341386/42472414-33d41b94-838f-11e8-943f-8c525c657b2c.png)
and on 3.8.2, it mounts and works but is extremely slow. Even if I use `-odefer_permissions,noappledouble` it still takes 5 seconds to cd in a folder

**Comment by Qiaoyf96** [comment] 2018-07-09 19:59
@MuhsinFatih You must have the sudo permission on this, like:
```
sudo ls ~/mount/aws
```

**Comment by MuhsinFatih** [comment] 2018-07-10 03:04
@LegaDyan but I didn't mount with sudo

**Comment by alinicholls** [comment] 2018-07-24 14:28
Currently I am not able to run 3.8.2 with macOS 10.14 beta 4.  Is there a timeline for a FUSE update that will support this macOS version?  Many thanks!

**Comment by KizzyCode** [comment] 2018-07-24 17:42
On my 10.14 beta 4, version 3.8.2 works flawlessly. Can you give further information where it fails?

**Comment by alinicholls** [comment] 2018-07-25 09:22
Thanks for the reply - this led me to check my installation and I was on 3.8.0 but thought I had already installed 3.8.2 (testing on too many systems at once!).  I have now installed 3.8.2 and things are working for me :)

**Comment by docdyhr** [comment] 2018-09-08 21:20
@bfleischer Thank you for the good work making Keybase work on Mojave Beta!

**Comment by bfleischer** [comment] 2018-09-26 19:36
FUSE seems to be working well on Mojave, so I'm closing the issue.

**Closed as completed by bfleischer** 2018-09-26 19:36 UTC
Labels: enhancement

**Comment by yannperey** [comment] 2018-09-27 08:30
Sorry but the osxFuse is freezing on a fresh new Mojave system. Only option, kill the associated process. I'm using the official release of Mojave. Any clue on this ? (I've tried the 3.8.2 version)

**Comment by ebarchukov** [comment] 2018-09-27 14:22
For Transmit and sshfs... used this 'sudo cp -R /Library/Filesystems/osxfuse.fs/Contents/Extensions/10.13 /Library/Filesystems/osxfuse.fs/Contents/Extensions/10.14'
And it's working....

**Comment by bfleischer** [comment] 2018-09-27 14:39
@ebarchukov Don't do this! I cannot stress this enough. Please update FUSE to the latest version. 3.8.2 is compatible with macOS Mojave and does not require any hacks like using an incompatible kernel extension on 10.14. 

> And it's working....

It's not. Trust me.

**Comment by bfleischer** [comment] 2018-09-27 14:40
@yannperey Which file system are you using? Have you raised the issue with the file system developer?

**Comment by ebarchukov** [comment] 2018-09-27 14:44
> @ebarchukov Don't do this! I cannot stress this enough. Please update FUSE to the latest version. 3.8.2 is compatible with macOS Mojave and does not require any hacks like using an incompatible kernel extension on 10.14.
> 
> > And it's working....
> 
> It's not. Trust me.

3.8.2 - works... Thanks!

**Comment by yannperey** [comment] 2018-09-27 14:48
I’ve not raised anything as I do not know how to do it. I don’t know what else I can say except that I’m using the latest version of a Mojave (10.14) released on the 25th September officially by apple. 
Just starting the 3.8.2 installer which since 2 hours  is saying « Attente de la fin des autres installations » so something like « Waiting for the end of the other installations »...

**Comment by yannperey** [comment] 2018-09-27 14:56
Sorry, my bad. An old installation process of pCloud was still running in the background. Killing it allows me to run the osxFuse 3.8.2 without any issue on OS X Mojave. Sorry for that.

**Comment by eduardomart** [comment] 2018-10-02 01:55
Just installed 3.8.2 and ForkLift disklets seem to be working again! 🎉

**Comment by moreplavec** [comment] 2018-10-03 21:40
I tried to install 3.8.1 and 3.8.2, but installer stops with step to click Install. Clicking the button, but nothing happens.

**Comment by stubevan** [comment] 2018-10-09 16:05
I can confirm that 3.82 works.  3.8.0 did not.  The upgrade resolves that

**Comment by cristianmenghi** [comment] 2018-10-20 15:05
Hi, can't work automount with mojave and 3.8.2 from brew cask.

**Comment by ITguyAtlanta** [comment] 2018-10-26 18:15
I updated to Mojave, installed Fuse 3.8.2, but still getting mounting error and "Fuse too old for OS" error when trying to us Gladinet Cloud Suite Mac Client.
Any thoughts?

**Comment by GerZah** [comment] 2018-10-31 10:14
> [Edits added because @bfleischer said this is not a good idea]
> I think I may have found a functional [But Very Bad] solution to running OSXFuse on Mojave:
> In terminal [You probably shouldn’t]:
> sudo cp -R /Library/Filesystems/osxfuse.fs/Contents/Extensions/10.13 /Library/Filesystems/osxfuse.fs/Contents/Extensions/10.14

Yeah, I also upgraded to macOS 10.14 Mojave and found my VeryCrypt dysfunctional due to FUSE 3.7.1 reFUSEing to work (pun intended).

Believe me: I'd rarely blindly follow a "sudo cp -R /Library/…" instruction. But then again, I know my way around in the terminal.

I read from the other posters that FUSE often requires to be patched from one major OS version to the next. But then I checked my /Library/Filesystems/osxfuse.fs/Contents/Extensions/ – only to see that the 10.12 and 10.13 directories were actually symlinks to 10.11. So I did what I had to do:

`cd /Library/Filesystems/osxfuse.fs/Contents/Extensions/`
`sudo ln -s 10.11 10.14`

No worrisome recursive copying, merely the creation of a tiny little symlink. And guess what: VeryCrypt just mounted my .tc image without any more fuss. ;-)

———————

UPDATE: I just updated to FUSE 3.8.2, and guess what: They did the exact same thing:

`$ pwd`
`/Library/Filesystems/osxfuse.fs/Contents/Extensions`
`$ ls -l`
`total 0`
`lrwxr-xr-x  1 root  wheel   4 31 Okt 11:22 10.10 -> 10.9`
`drwxr-xr-x  3 root  wheel  96  1 Jul 19:00 10.11`
`lrwxr-xr-x  1 root  wheel   5 31 Okt 11:22 10.12 -> 10.11`
`lrwxr-xr-x  1 root  wheel   5 31 Okt 11:22 10.13 -> 10.11`
`lrwxr-xr-x  1 root  wheel   5 31 Okt 11:22 10.14 -> 10.11`
`drwxr-xr-x  3 root  wheel  96  1 Jul 19:00 10.5`
`drwxr-xr-x  3 root  wheel  96  1 Jul 19:00 10.6`
`lrwxr-xr-x  1 root  wheel   4 31 Okt 11:22 10.7 -> 10.6`
`lrwxr-xr-x  1 root  wheel   4 31 Okt 11:22 10.8 -> 10.6`
`drwxr-xr-x  3 root  wheel  96  1 Jul 19:00 10.9`
`$`

So 10.14 is still a symlink to 10.11, now straight out of the installer.

**Comment by bfleischer** [comment] 2018-10-31 10:42
@GerZah I explained this multiple times. The FUSE kernel extension checks the version of macOS at runtime and acts accordingly. The version of FUSE you are using is too old for Mojave and does not contain a code path for Mojave. That's why there is no symlink. Version 3.7.1 does **NOT** support Mojave! The kernel extension accesses private kernel structs, that have changed in Mojave. Please stop advocating creating a symlink if you don't know all the details. That you know your way around in Terminal does not compensate for that. What makes this worse is that you even quoted my original post just to advocate against it.

**Comment by GerZah** [comment] 2018-10-31 10:51
@bfleischer Sorry for stepping on your toes. I hear what you are saying, all I can say is: As 3.7.1 did not offer the 3.8.2 update (I had to manually download and install, which I did only afterwards), so I dabbled around with symlinking 3.11 support to 3.14 in 3.7.1 … which should not have worked, but believe it or not, it did.

Anyway – what do you want me to do? Should I delete my followup post above?

**Comment by KizzyCode** [comment] 2018-10-31 11:09
@GerZah Oh, it may have worked but you have a huge risk of undefined behavior – the KEXT misinterprets and even worse creates invalid structures that can go rogue in the kernel.

If sth. goes wrong (because a more exotic feature is used which is placed at the wrong location in a structure etc.) the damage could range from a simple kernel panic over irreparable (silent) damage in your FUSE-volumes up to undefined behavior and possibly silent corruption in other system components (loss of **all** data etc.). 

(And that 10.14 is a symlink to 10.11 does not matter because the version in 10.11 is a new one that can detect and handle Mojave)

Therefore I completely agree with @bfleischer – unless you’re on a **test machine** which cannot access any important hard drives etc. you should **never ever** load a KEXT that uses private kernel APIs and has not been updated to your OS. This is not limited to FUSE but also affects NVIDIA’s graphic driver for example.

**Comment by daynaskully** [comment] 2018-12-07 14:32
I'm having the same issue of 3.8 not working with mojave.
