### ISSUE TITLE
3.8.2 always crashes Finder, and now it crashed whole MacOS!

### ISSUE THREAD

**Issue by nickolaym** [osxfuse/osxfuse#556] opened 2018-11-29 09:30 UTC
Finder crashes every day, sometimes every few hours.
This night the OS crashed. Here is the panic report it displayed after reboot.

```
Anonymous UUID:       B8CB806C-D507-23DA-CE83-1676A13D1678

Thu Nov 29 09:00:39 2018

*** Panic Report ***
panic(cpu 4 caller 0xffffff80036d84dd): Kernel trap at 0xffffff8003393333, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0xffffff850dff7b4c, CR3: 0x00000004579fa036, CR4: 0x00000000001626e0
RAX: 0x00000000abc18a17, RBX: 0xffffff81a0558400, RCX: 0xffffff81a0558800, RDX: 0x0302010200000001
RSP: 0xffffff922d573ac0, RBP: 0xffffff922d573b30, RSI: 0xffffff81a0558000, RDI: 0x000000013611ada4
R8:  0xffffff85da768f84, R9:  0xffffff850dff7b4c, R10: 0xffffff83950b01a0, R11: 0xffffff81a0558800
R12: 0xfffffe91a0bbe000, R13: 0xffffff81a0558ffe, R14: 0x0000000000000001, R15: 0x0000000000000990
RFL: 0x0000000000010212, RIP: 0xffffff8003393333, CS:  0x0000000000000008, SS:  0x0000000000000000
Fault CR2: 0xffffff850dff7b4c, Error code: 0x0000000000000000, Fault CPU: 0x4, PL: 1, VF: 5

Backtrace (CPU 4), Frame : Return Address
0xffffff922d573590 : 0xffffff80035aca9d 
0xffffff922d5735e0 : 0xffffff80036e6893 
0xffffff922d573620 : 0xffffff80036d82ba 
0xffffff922d573690 : 0xffffff8003559ca0 
0xffffff922d5736b0 : 0xffffff80035ac4b7 
0xffffff922d5737d0 : 0xffffff80035ac303 
0xffffff922d573840 : 0xffffff80036d84dd 
0xffffff922d5739b0 : 0xffffff8003559ca0 
0xffffff922d5739d0 : 0xffffff8003393333 
0xffffff922d573b30 : 0xffffff80036282dc 
0xffffff922d573b90 : 0xffffff8003627e62 
0xffffff922d573bd0 : 0xffffff8003629e34 
0xffffff922d573c10 : 0xffffff8003632ef0 
0xffffff922d573d20 : 0xffffff800363767a 
0xffffff922d573f10 : 0xffffff80036d88b5 
0xffffff922d573fa0 : 0xffffff8003559baf 

BSD process name corresponding to current thread: loginwindow

Mac OS version:
18B75

Kernel version:
Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64
Kernel UUID: 5D53F7E4-472A-369D-97D8-4DD877A4BDFF
Kernel slide:     0x0000000003200000
Kernel text base: 0xffffff8003400000
__HIB  text base: 0xffffff8003300000
System model name: MacBookPro11,3 (Mac-2BD1B31983FE1663)

System uptime in nanoseconds: 92419877051208
last loaded kext at 92388724396265: com.apple.driver.usb.cdc	5.0.0 (addr 0xffffff7f8577d000, size 28672)
last unloaded kext at 53624082328363: com.apple.driver.usb.cdc	5.0.0 (addr 0xffffff7f8577d000, size 28672)
loaded kexts:
com.github.osxfuse.filesystems.osxfuse	3.8.2
org.virtualbox.kext.VBoxNetAdp	5.2.18
org.virtualbox.kext.VBoxNetFlt	5.2.18
org.virtualbox.kext.VBoxUSB	5.2.18
org.virtualbox.kext.VBoxDrv	5.2.18
com.apple.filesystems.smbfs	3.3.1
com.apple.driver.AppleHWSensor	1.9.5d0
com.apple.driver.AppleGraphicsDevicePolicy	3.25.6
com.apple.AGDCPluginDisplayMetrics	3.25.6
com.apple.driver.AppleHV	1
com.apple.fileutil	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.filesystems.autofs	3.0
com.apple.iokit.IOBluetoothSerialManager	6.0.9f2
com.apple.driver.pmtelemetry	1
com.apple.driver.ApplePlatformEnabler	2.7.0d0
com.apple.driver.AGPM	110.23.46
com.apple.driver.X86PlatformShim	1.0.0
com.apple.driver.AppleUpstreamUserClient	3.6.5
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AudioAUUC	1.70
com.apple.driver.AGDCBacklightControl	3.25.6
com.apple.GeForce	12.0.0
com.apple.driver.AppleIntelHD5000Graphics	12.0.2
com.apple.driver.AppleHDA	282.10
com.apple.driver.eficheck	1
com.apple.driver.AppleThunderboltIP	3.1.2
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleMuxControl	3.25.6
com.apple.driver.AppleLPC	3.1
com.apple.driver.AirPort.BrcmNIC	1400.1.1
com.apple.driver.AppleSMCLMU	212
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleMCCSControl	1.5.6
com.apple.driver.AppleIntelFramebufferAzul	12.0.2
com.apple.driver.AppleCameraInterface	6.8.0
com.apple.driver.AppleUSBCardReader	456.200.8
com.apple.driver.AppleUSBTCKeyboard	254
com.apple.driver.AppleUSBTCButtons	254
com.apple.driver.AppleVirtIO	2.0.9
com.apple.filesystems.hfs.kext	407.200.4
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.AppleSystemPolicy	1.0
com.apple.filesystems.apfs	945.220.38
com.apple.driver.AppleAHCIPort	329.200.2
com.apple.private.KextAudit	1.0
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	6.1
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	190
com.apple.security.TMSafetyNet	8
com.apple.driver.usb.cdc	5.0.0
com.apple.driver.AppleUSBAudio	315.6
com.apple.iokit.IOAVBFamily	710.1
com.apple.plugin.IOgPTPPlugin	700.7
com.apple.iokit.IOEthernetAVBController	1.1.0
com.apple.iokit.IOUSBUserClient	900.4.2
com.apple.kext.triggers	1.0
com.apple.driver.AppleSSE	1.0
com.apple.nvidia.driver.NVDAGK100Hal	12.0.0
com.apple.nvidia.driver.NVDAResman	12.0.0
com.apple.AppleGPUWrangler	3.25.6
com.apple.driver.DspFuncLib	282.10
com.apple.kext.OSvKernDSPLib	527
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IONDRVSupport	530
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.AppleHDAController	282.10
com.apple.iokit.IOHDAFamily	282.10
com.apple.driver.AppleGraphicsControl	3.25.6
com.apple.iokit.IOAudioFamily	206.5
com.apple.vecLib.kext	1.2.0
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.driver.corecapture	1.0.4
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.AppleGraphicsDeviceControl	3.25.6
com.apple.iokit.IOAcceleratorFamily2	400.27
com.apple.iokit.IOGraphicsFamily	530.12
com.apple.iokit.IOSurface	255.1
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	6.0.9f2
com.apple.iokit.IOBluetoothHostControllerUSBTransport	6.0.9f2
com.apple.iokit.IOBluetoothHostControllerTransport	6.0.9f2
com.apple.iokit.IOBluetoothFamily	6.0.9f2
com.apple.driver.usb.AppleUSBHub	1.2
com.apple.driver.AppleUSBMultitouch	263
com.apple.driver.usb.IOUSBHostHIDDevice	1.2
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.iokit.IOSerialFamily	11
com.apple.filesystems.hfs.encodings.kext	1
com.apple.iokit.IOAHCIBlockStorage	301.200.2
com.apple.iokit.IOAHCIFamily	288
com.apple.driver.AppleThunderboltDPInAdapter	5.5.8
com.apple.driver.AppleThunderboltDPAdapterFamily	5.5.8
com.apple.driver.AppleThunderboltPCIDownAdapter	2.1.4
com.apple.driver.AppleThunderboltNHI	4.7.6
com.apple.iokit.IOThunderboltFamily	6.8.1
com.apple.driver.usb.AppleUSBXHCIPCI	1.2
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.2
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOSMBusFamily	1.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.security.quarantine	3
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.DiskImages	493.0.0
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	456.200.8
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.kext.CoreTrust	1
com.apple.iokit.IOUSBMassStorageDriver	145.200.2
com.apple.iokit.IOSCSIBlockCommandsDevice	408.200.1
com.apple.iokit.IOSCSIArchitectureModelFamily	408.200.1
com.apple.iokit.IOStorageFamily	2.1
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.iokit.IOTimeSyncFamily	700.7
com.apple.iokit.IONetworkingFamily	3.4
com.apple.iokit.IOReportFamily	47
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.corecrypto	1.0

EOF
Model: MacBookPro11,3, BootROM 149.0.0.0.0, 4 processors, Intel Core i7, 2,5 GHz, 16 GB, SMC 2.19f12
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Graphics: NVIDIA GeForce GT 750M, NVIDIA GeForce GT 750M, PCIe
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.77.61.1 AirPortDriverBrcmNIC-1305.2)
Bluetooth: Version 6.0.9f2, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512F, 500,28 GB
USB Device: USB 3.0 Bus
USB Device: Internal Memory Card Reader
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: Logitech USB Headset
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1
```

**Comment by bfleischer** [comment] 2018-12-14 17:23
FUSE is not to blame for this crash. The backtrace of kernel functions that lead to the crash does not contain any FUSE function call. What makes you believe FUSE is to blame, other than the fact that the FUSE kernel extension was loaded at the time of the crash?

Here the symbolicated backtrace:

```
Backtrace (CPU 4), Frame : Return Address
0xffffff922d573590 : 0xffffff80035aca9d handle_debugger_trap (in kernel) (debug.c:885)
0xffffff922d5735e0 : 0xffffff80036e6893 kdp_i386_trap (in kernel) (cpu_data.h:560)
0xffffff922d573620 : 0xffffff80036d82ba kernel_trap (in kernel) (trap.c:776)
0xffffff922d573690 : 0xffffff8003559ca0 trap_from_kernel (in kernel) + 38
0xffffff922d5736b0 : 0xffffff80035ac4b7 panic_trap_to_debugger (in kernel) (debug.c:755)
0xffffff922d5737d0 : 0xffffff80035ac303 panic (in kernel) (debug.c:0)
0xffffff922d573840 : 0xffffff80036d84dd kernel_trap (in kernel) (trap.c:833)
0xffffff922d5739b0 : 0xffffff8003559ca0 trap_from_kernel (in kernel) + 38
0xffffff922d5739d0 : 0xffffff8003393333 WKdm_decompress_new (in kernel) + 467
0xffffff922d573b30 : 0xffffff80036282dc c_decompress_page (in kernel) (vm_compressor.c:0)
0xffffff922d573b90 : 0xffffff8003627e62 vm_compressor_get (in kernel) (vm_compressor.c:3957)
0xffffff922d573bd0 : 0xffffff8003629e34 vm_compressor_pager_get (in kernel) (vm_compressor_pager.c:841)
0xffffff922d573c10 : 0xffffff8003632ef0 vm_fault_page (in kernel) (vm_fault.c:1571)
0xffffff922d573d20 : 0xffffff800363767a vm_fault_internal (in kernel) (vm_fault.c:4585)
0xffffff922d573f10 : 0xffffff80036d88b5 user_trap (in kernel) (trap.c:1102)
0xffffff922d573fa0 : 0xffffff8003559baf hndl_alltraps (in kernel) + 223
```

It looks like the issue is somehow triggered when the login window tries to access compressed RAM. Please report the issue to Apple.

**Comment by nickolaym** [comment] 2019-02-01 00:32
This crash appears only after I mount a remote volume.
So it makes me blame.
Maybe FUSE just triggers my system to go to the fall, - some specific memory layout... I don't know.

**Comment by Dauphin38** [comment] 2019-03-10 17:02
Finder crash with 3.8.3 and Mojave bêta 10.14.4 (18E205e)

**Comment by bfleischer** [comment] 2019-05-04 13:08
Since there have not been any new insights, I'm closing the issue.

**Closed as completed by bfleischer** 2019-05-04 13:08 UTC
Labels: need more info
