### ISSUE TITLE
sshfs freezes system after failure of login

### ISSUE THREAD

**Issue by seheatwole** [osxfuse/osxfuse#668] opened 2020-01-10 13:08 UTC
When I mess up the pin for my login or the connection fails, osxfuse locks up finder and gradually the rest of the system locks up and requires a hard reboot to clear.

I am on a 2019 Macbook Pro with MacOS Mojave 10.14.6
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
OSXFUSE 3.10.3
FUSE library version: 2.9.7

**Comment by chfanghr** [comment] 2020-11-19 02:34
Same here with Big Sur 11.0.1. Any progress after 10 months?

**Comment by zebu1er** [comment] 2020-11-29 14:32
Same on OSX10.15...

**Comment by Andrysky** [comment] 2021-01-05 11:33
on OSX10.15.7
macFUSE 4.0.5
SSHFS 2.5.0

I use the key in ssh-agent, so the login should be successful, because ssh works


maybe you need some kind of logs?

**Comment by dagi3d** [comment] 2021-01-28 16:13
same here...

**Comment by wglas85** [comment] 2021-02-04 20:07
Same here, on OSX10.15.7 macFUSE 4.0.5, SSHFS 2.5.0.
This is really annoying and lead to a series fo hard reboots and is rendering osxfuse unacceptable for us.
What kind of logfiles may we provide in order to analyse the problem?

**Comment by bfleischer** [comment] 2021-02-04 20:15
I think this issue needs to be addressed in SSHFS, not macFUSE. At least SSHFS would be the logical start point for investigating this issue. My main focus is macFUSE, not SSHFS. If anybody wants to take a shot at this, help is always welcome.

**Comment by tbrodbeck** [comment] 2021-05-17 16:23
> on OSX10.15.7
> macFUSE 4.0.5
> SSHFS 2.5.0
> 
> I use the key in ssh-agent, so the login should be successful, because ssh works
> 
> maybe you need some kind of logs?

Same problem still and sshutil does not work at all... How can I activate logs?

sshfs gives me no output at all and I have to restart to be able to use my system again.. :(

**Comment by grischard** [comment] 2021-05-17 20:52
macFUSE 4.1.1, released a few days ago, fixed "an issue when mounting a volume that can, in rare cases, result in the file system process crashing". Does this still happen in 4.1.2 which was released today?

**Comment by tbrodbeck** [comment] 2021-05-18 07:16
> macFUSE 4.1.1, released a few days ago, fixed "an issue when mounting a volume that can, in rare cases, result in the file system process crashing". Does this still happen in 4.1.2 which was released today?

Yes I am using macFUSE 4.1.12

**Comment by tbrodbeck** [comment] 2021-05-18 18:05
> macFUSE 4.1.1, released a few days ago, fixed "an issue when mounting a volume that can, in rare cases, result in the file system process crashing". Does this still happen in 4.1.2 which was released today?

Okay I found the reason for my freeze.
In my case I was calling `zsh; exit` in my bashrc (because the server was using bash by default). This caused my sshfs to freeze!

**Comment by Andrysky** [comment] 2021-05-18 19:31
> > macFUSE 4.1.1, released a few days ago, fixed "an issue when mounting a volume that can, in rare cases, result in the file system process crashing". Does this still happen in 4.1.2 which was released today?
> 
> Okay I found the reason for my freeze.
> In my case I was calling `zsh; exit` in my bashrc (because the server was using bash by default). This caused my sshfs to freeze!

🤣🤣👍🔥

**Comment by grischard** [comment] 2021-05-20 17:09
Can anyone else reproduce this with 4.1.2?

**Comment by tyzhnenko** [comment] 2021-07-18 19:34
Got the same :(

```
$ sshfs --version
SSHFS version 2.10
FUSE library version: 2.9.9
fuse: no mount point
```

```
$ sshfs --version
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
FUSE library version: 2.9.9
fuse: no mount point
```

both freeze :(

macFUSE – 4.1.2

**Comment by etsiaDigital** [comment] 2021-09-30 21:09
Froze everything for me.  Kind of hard to troubleshoot...  hard freeze.  Had to recycle everything.  I don't know if it was the egg or the chicken and I don't have the time right now to hunt or chase.  Same versions as  tyzhnenko  
bummer

**Comment by mwort** [comment] 2021-11-03 12:05
Same here, this is really annoying and I'm not getting any output from sshfs:
```
SSHFS version 2.10.0
FUSE library version: 2.9.9
fuse: no mount point
```

**Comment by rryan** [comment] 2021-12-20 05:44
Fresh install of macFUSE 4.2.3 and SSHFS 2.5.0 today on macOS 11.6.1:
```
sshfs --version
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
FUSE library version: 2.9.9
fuse: no mount point
```

I hit ^C at the password prompt and it triggered this hang. Had to hard reboot.

**Edit:** Hm, it appears I had version 3.11.2 of osxfuse from Homebrew installed. Removed and the `--version` output is the same.

**Comment by rlam3** [comment] 2022-12-28 18:35
This seems to be a consistent problem. Do you know if this is going to be resolved in a patch or fix?

**Comment by ToeKneeFan** [comment] 2023-04-14 20:12
I am not sure, but this may be the same problem as #856. Some users have reported some success by just uninstalling and reinstalling while on a newer macOS version (sounds like 12.1 and above) (https://github.com/osxfuse/osxfuse/issues/856#issuecomment-1012141230):

> Not sure if this will help anyone, but `sshfs` was hanging on my m1 mac, but is now working 🎉
> 
> Unsure what fixed the issue but I did the following:
> 
> - Removed macFUSE (installed from https://osxfuse.github.io/)
> - Restart
> - Updated macOS from `12.0.1` to `12.1`
> - Install macFUSE via brew (e.g. `brew install --cask macfuse`)
> - Restart
> - Then `sshfs` working 
> 
> Sorry if that doesn't resolve your issue, I'll update if I have any further issues.
> > >

**Comment by bfleischer** [comment] 2024-03-16 11:49
The new 4.6.2 release addresses the hang.

**Closed as completed by bfleischer** 2024-03-16 11:49 UTC
Labels: bug
