### ISSUE TITLE
Forget VPN == macFUSE locks up the OS

### ISSUE THREAD

**Issue by FGasper** [osxfuse/osxfuse#826] opened 2021-06-24 14:34 UTC
1. Attempt to `sshfs -o noapplexattr -o noappledouble root@felipe.dev.cpanel.net:/whatever /some/local/path`. Note that sshfs will stall. CTRL-C to end it.

2. Type `mount`, and see that the mount table lists the mount, even though the SSH connection will have failed.

3. Note that Chrome, Brave, et al. fail to load anything … they sit there spinning for a long time but never actually load a page. (Firefox, though, will work.)

4. Try the `sshfs` command again, and note that you’ve lost all control over that process.

5. Note that even `sudo umount -f /some/local/path` fails: `Resource busy`

-----
The failure is step 1, for me, is because I forgot to start up the VPN before running `sshfs` … which is what those outside my organization should also see.

I’m not sure if this is an `sshfs` or a macFUSE problem. I’ve dealt with it for some time now but only just now realized reliable reproduction steps.

Thank you for your time!

**Comment by FGasper** [comment] 2021-06-24 14:41
I note that the same behaviour manifests if I *do* have the VPN on but neglect to `ssh-add` the key then also CTRL-C out when sshfs asks me to `Enter passphrase for key …`.

I believe this bug wasn’t formerly _quite_ so reliable, but I don’t know for certain.

**Comment by pslack** [comment] 2021-07-13 14:40
I had a similar freeze experience, my reproducible step; trying to mount on local /Volumes, that seems to be a very bad idea but I didn't have any info to say otherwise, as soon as I mounted outside of that (ex I used /opt/somemountpoint) I was fine, no more freezing

**Comment by johnsalmon** [comment] 2021-10-19 15:26
The inability to unmount makes me wonder if this is related:  https://github.com/osxfuse/osxfuse/issues/793#issuecomment-945151674  If a FUSE client "successfully" mounts, but then doesn't respond to getattr, statfs, etc., it can make it impossible to shut down.

**Comment by epaterlini** [comment] 2022-10-20 12:44
Same problem here, this is very frustrating. Every time I run the command sshfs if, for some reason, connectivity cannot be estabilished or I press CTRL-C, the entire system goes into unusable state! I have to hard reboot...this is not nice at all :-(

**Comment by moinessim** [comment] 2022-11-02 23:34
Same problem here

**Comment by bfleischer** [comment] 2024-03-08 16:11
The issue is fixed in the next macFUSE release. See https://github.com/osxfuse/osxfuse/issues/793#issuecomment-1985966465 for details.

**Closed as completed by bfleischer** 2024-03-08 16:11 UTC
Labels: bug

**Comment by bfleischer** [comment] 2024-03-16 12:22
The new 4.6.2 release addresses this issue. Let me know in case you are still running into mount issues.
