### ISSUE TITLE
System Extension Failed

### ISSUE THREAD

**Issue by 4pastor** [osxfuse/osxfuse#947] opened 2023-04-15 18:41 UTC
I am trying to open VeraCrypt and getting the following alerts. Can anyone help, please?

<img width="273" alt="Screenshot 2023-04-15 at 14 00 13" src="https://user-images.githubusercontent.com/96359391/232247733-563b16a5-bb16-4ed8-99e3-804589579068.png">

<img width="270" alt="Screenshot 2023-04-15 at 14 00 35" src="https://user-images.githubusercontent.com/96359391/232247750-8661ed0b-420c-4ed3-bc62-cdb548fbac7f.png">

**Comment by bfleischer** [comment] 2023-04-18 22:41
Duplicate of #946

**Closed as completed by bfleischer** 2023-04-18 22:41 UTC
Labels: duplicate
