### ISSUE TITLE
Installation of latest FUSE fails on High Sierra

### ISSUE THREAD

**Issue by jimrome** [osxfuse/osxfuse#447] opened 2017-11-09 13:58 UTC
"The installer encountered an error that caused the installation to fail"

**Comment by radj** [comment] 2017-11-10 10:01
* Is this version 3.7.1?
* Where did you pick it up from?
* Can you spot anything fishy in `/var/log/install.log`?

We've been testing this here on High Sierra and our installs for 3.7.1 DMG downloaded from releases page always succeeds. Can even update fine from System Preferences.

**Comment by jimrome** [comment] 2017-11-11 13:23
The update to FUSE worked from the preference pane.

**Comment by stvcisco** [comment] 2017-11-11 15:56
I'm trying a new install and it fails because the signature. Pressing "Allow" on the security preferences does nothing so the install can't complete. (yes, with 3.7.1)

**Comment by stvcisco** [comment] 2017-11-11 16:23
Interesting... I exited MagicPrefs and tried again, and it allowed the "Allow".  Not sure why that mattered, but it unblocked me.

**Comment by iomz** [comment] 2017-11-12 01:36
I have the same issue with @stvcisco.
The version is also 3.7.1 but pressing "Allow" button on Security & Privacy > General doesn't do anything.
Not using MagicPrefs.

**Comment by baldr1k** [comment] 2017-11-21 04:52
I have the same issue as @iomz. Not using MagicPrefs

**Comment by pirana-sas** [comment] 2017-11-22 11:29
If you use a wacom (as we do) nothing happens when clicking on Allow. But when we clicked it using a normal mouse, it worked. Maybe this will solve it also for you.

**Comment by iomz** [comment] 2017-11-26 04:00
Although it's not a essential solution, I disabled SPI in Recovery Mode (boot pressing &#8984;+r and `# csrutil disable`) to detour all the third party kernel extension security thing and kept it disabled. So far I'm able to use FUSE like before.

Looks like High Sierra has issues around this KEXT blocking.
Found a thread about VMWare extension: https://discussions.apple.com/thread/8087342

**Comment by cgarrigues** [comment] 2017-12-10 18:28
I had a similar issue to pirana-sas. I was remotely logged into the system and it didn't work. When I got on the actual screen the click did work.

There is apparently a security check to assure that you're using the local mouse to Allow access.

I guess this makes sense.

**Comment by bfleischer** [comment] 2018-05-11 20:47
Duplicate of #437.

**Closed as completed by bfleischer** 2018-05-11 20:47 UTC
Labels: duplicate

**Comment by arevaloaraque** [comment] 2018-08-28 02:08
I used the the keyboard to press "Allow" button and it's works for me. If you press button using click does not works.

**Comment by MichalMisiaszek** [comment] 2019-03-07 05:27
> I used the the keyboard to press "Allow" button and it's works for me. If you press button using click does not works.

Amazing but true! Thanks

**Comment by ocverclock** [comment] 2019-06-24 08:27
for me egal

**Comment by stefkes** [comment] 2019-06-29 01:54
@arevaloaraque  how do you use the keyboard to press Allow? I can't tab on to the button to press enter. Clicking the mouse does nothing.

EDIT: clicking with the mouse works after closing VLC
