### ISSUE TITLE
build error on Mac OS X 10.6 with MacPorts

### ISSUE THREAD

**Issue by dliessi** [osxfuse/osxfuse#318] opened 2016-09-24 19:02 UTC
During `BUILD NATIVE TARGET mount_osxfuse OF PROJECT mount_osxfuse WITH CONFIGURATION Release`:
```
cc1: warnings being treated as errors
/Volumes/MacPorts/hopeful/build/_opt_macports-git_trunk_dports_fuse_osxfuse/osxfuse/work/osxfuse-osxfuse-cc7d953/support/mount_osxfuse/mount_osxfuse.c: In function 'send_fd':
/Volumes/MacPorts/hopeful/build/_opt_macports-git_trunk_dports_fuse_osxfuse/osxfuse/work/osxfuse-osxfuse-cc7d953/support/mount_osxfuse/mount_osxfuse.c:603: warning: implicit conversion shortens 64-bit value into a 32-bit value
```
and during `BUILD NATIVE TARGET osxfuse.fs OF PROJECT osxfusefs WITH CONFIGURATION Release`
```
pbxcp: mount_osxfuse: No such file or directory
pbxcp: mount_osxfuse: No such file or directory
```

Let me know if you need further information.

**Comment by bfleischer** [comment] 2016-09-26 19:28
Thanks for the bug report. The issue is fixed in commit https://github.com/osxfuse/support/commit/598c9bbca5fa99903fbf47035edc8e731124758d.

**Closed by bfleischer** 2016-09-26 19:28 UTC
