### ISSUE TITLE
Duplicate prefpane after installing 4.0.0

### ISSUE THREAD

**Issue by Cyberbeni** [osxfuse/osxfuse#736] opened 2020-10-30 09:45 UTC
Updating through the old pref pane failed and when I downloaded the installer manually and installed the update (it said update for both the framework and the prefpane), the old prefpane remained but a new one (macFUSE) also appeared.

**Comment by bfleischer** [comment] 2020-10-30 09:49
Thanks for reporting the bug. Until the issue is fixed, you can remove the old preference pane manually by ctrl-clicking on it and selecting "Remove ..." in the context menu.

**Comment by bfleischer** [comment] 2020-11-01 16:07
The issue is fixed in the upcoming 4.0.1 release. Upgrading from version 3 to version 4.0.1 will remove all files from version 3.

**Closed as completed by bfleischer** 2020-11-01 16:07 UTC
Labels: bug
