### ISSUE TITLE
osxfuse crashes if -odebug is not supplied to fuse_main

### ISSUE THREAD

**Issue by Bob590** [osxfuse/osxfuse#604] opened 2019-07-17 18:28 UTC
I'm experiencing a strange behavior in a experimental fuse application.
If I call fuse_main with argv that specify -odebug all works and of course I get the log in my debugger console. If I omit this option the program crashes.
Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY
The parameters that I specify on fuse_main are:
-oallow_other,auto_xattr,daemon_timeout=180,fsname=MYFS,local,nolocalcaches,kill_on_unmount,noappledouble

I'm adding ",debug" at the end of this string to enable debug printing.
So if I omit this piece the program crashes!

Any clue?

**Comment by bfleischer** [comment] 2019-07-17 18:42
`-odebug` implicitly adds `-f`. The file system runs in foreground mode. I'm assuming your file system does not like running as daemon. Have you tried using the `-f` option instead of `-odebug`?

**Comment by Bob590** [comment] 2019-07-18 06:39
Sorry, maybe I have not explained it well. The problem is opposite. If I DONT'T put -odebug the program crashes. If I put it then all is working well. I wish to eliminate the debug log.

**Comment by Bob590** [comment] 2019-07-18 06:47
BTW: I have tried versions 3.9.0, 3.9.1, 3.10.0 and all behave the same. My User mode file system is written in Qt and running on Mac Osx Mojave. The odd is that the crash report tell me that crashes in get_attr but I'm not able to put a breakpoint there. I mean that I put the breakpoint at the crash line (as the Console App tell me) but it crashes and the breakpoint doesn't hit. With the -odebug option, instead, the breakpoint hit. Really odd behavior.

**Comment by Bob590** [comment] 2019-07-18 07:08
TEST RESULT: Adding -f with or without -odebug seems to solve the problem. Please can you explain me what the -f is doing? Thank you. I have mainly cloned the loopback example to build my file system.

**Comment by bfleischer** [comment] 2019-07-18 07:11
I'm assuming there is a bug in your file system that causes the crash when your file system runs in background as a daemon. Running it with `-f` instead of `-odebug` keeps your file system in foreground without printing the debug logs.

**Comment by Bob590** [comment] 2019-07-18 07:35
That's exactly what I have done and you see above my results. Please can you explain me the difference between with or without -f ?

**Comment by Bob590** [comment] 2019-07-18 07:51
I forgot to mention that I was also using the -s option to have my file system working. Now I have put -f without -s and it works well. In this way the -odebug is don't care (with or without always works).

**Comment by bfleischer** [comment] 2019-07-21 14:03
Without having access to the source code of your file system I can only guess, but it looks like your file system is not thread safe and does not handle well being being run as daemon. This can have various reasons. However since this is not a bug in FUSE for macOS, I'm closing the issue.

**Comment by Bob590** [comment] 2019-07-22 16:19
Yes, that could be the case. I'll investigate to find where the problem could be. Meanwhile my file system works well with the -f option and thus I'm doing my experiments with it for now.
Thank you for your support!

**Closed as completed** 2019-07-26 04:04 UTC
Labels: question
